//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Silverlight.Resources.Fraude {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galatee.Silverlight.Resources.Fraude.Langue", typeof(Langue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElementDansTable.
        /// </summary>
        internal static string ElementDansTable {
            get {
                return ResourceManager.GetString("ElementDansTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErreurInsertionDonnees.
        /// </summary>
        internal static string ErreurInsertionDonnees {
            get {
                return ResourceManager.GetString("ErreurInsertionDonnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de saisie.
        /// </summary>
        internal static string Fraude {
            get {
                return ResourceManager.GetString("Fraude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl_ListeCentre.
        /// </summary>
        internal static string lbl_ListeCentre {
            get {
                return ResourceManager.GetString("lbl_ListeCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl_Menu.
        /// </summary>
        internal static string lbl_Menu {
            get {
                return ResourceManager.GetString("lbl_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MsgEltInexistent.
        /// </summary>
        internal static string MsgEltInexistent {
            get {
                return ResourceManager.GetString("MsgEltInexistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to msgErreurChargementDonnees.
        /// </summary>
        internal static string msgErreurChargementDonnees {
            get {
                return ResourceManager.GetString("msgErreurChargementDonnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez vous enregistrer.
        /// </summary>
        internal static string QuestionEnregistrerDonnees {
            get {
                return ResourceManager.GetString("QuestionEnregistrerDonnees", resourceCulture);
            }
        }

        public static string RecuperationEchec { get; set; }
    }
}
