//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Galatee.Silverlight.ServiceSig {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CsPrint", Namespace="http://schemas.datacontract.org/2004/07/Galatee.Structure")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Galatee.Silverlight.ServiceSig.CsClientRechercher))]
    public partial class CsPrint : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CsClientRechercher", Namespace="http://schemas.datacontract.org/2004/07/Galatee.Structure")]
    public partial class CsClientRechercher : Galatee.Silverlight.ServiceSig.CsPrint {
        
        private string ADRESSEELECTRIQUEField;
        
        private decimal AVANCEField;
        
        private string CENTREField;
        
        private string CLIENTField;
        
        private string FACTUREField;
        
        private int FK_IDABONField;
        
        private int FK_IDCENTREField;
        
        private string LATITUDEField;
        
        private string LONGITUDEField;
        
        private string LOTField;
        
        private string NOMABONField;
        
        private string NUMCOMPTEURField;
        
        private string ORDREField;
        
        private int OptionRechercheField;
        
        private string PERIODEField;
        
        private int PK_IDField;
        
        private int POINTField;
        
        private string PORTEField;
        
        private string PRODUITField;
        
        private string RUEField;
        
        private string SEQUENCEField;
        
        private string TOURNEEField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADRESSEELECTRIQUE {
            get {
                return this.ADRESSEELECTRIQUEField;
            }
            set {
                if ((object.ReferenceEquals(this.ADRESSEELECTRIQUEField, value) != true)) {
                    this.ADRESSEELECTRIQUEField = value;
                    this.RaisePropertyChanged("ADRESSEELECTRIQUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AVANCE {
            get {
                return this.AVANCEField;
            }
            set {
                if ((this.AVANCEField.Equals(value) != true)) {
                    this.AVANCEField = value;
                    this.RaisePropertyChanged("AVANCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CENTRE {
            get {
                return this.CENTREField;
            }
            set {
                if ((object.ReferenceEquals(this.CENTREField, value) != true)) {
                    this.CENTREField = value;
                    this.RaisePropertyChanged("CENTRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLIENT {
            get {
                return this.CLIENTField;
            }
            set {
                if ((object.ReferenceEquals(this.CLIENTField, value) != true)) {
                    this.CLIENTField = value;
                    this.RaisePropertyChanged("CLIENT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FACTURE {
            get {
                return this.FACTUREField;
            }
            set {
                if ((object.ReferenceEquals(this.FACTUREField, value) != true)) {
                    this.FACTUREField = value;
                    this.RaisePropertyChanged("FACTURE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_IDABON {
            get {
                return this.FK_IDABONField;
            }
            set {
                if ((this.FK_IDABONField.Equals(value) != true)) {
                    this.FK_IDABONField = value;
                    this.RaisePropertyChanged("FK_IDABON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FK_IDCENTRE {
            get {
                return this.FK_IDCENTREField;
            }
            set {
                if ((this.FK_IDCENTREField.Equals(value) != true)) {
                    this.FK_IDCENTREField = value;
                    this.RaisePropertyChanged("FK_IDCENTRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LATITUDE {
            get {
                return this.LATITUDEField;
            }
            set {
                if ((object.ReferenceEquals(this.LATITUDEField, value) != true)) {
                    this.LATITUDEField = value;
                    this.RaisePropertyChanged("LATITUDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LONGITUDE {
            get {
                return this.LONGITUDEField;
            }
            set {
                if ((object.ReferenceEquals(this.LONGITUDEField, value) != true)) {
                    this.LONGITUDEField = value;
                    this.RaisePropertyChanged("LONGITUDE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOT {
            get {
                return this.LOTField;
            }
            set {
                if ((object.ReferenceEquals(this.LOTField, value) != true)) {
                    this.LOTField = value;
                    this.RaisePropertyChanged("LOT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMABON {
            get {
                return this.NOMABONField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMABONField, value) != true)) {
                    this.NOMABONField = value;
                    this.RaisePropertyChanged("NOMABON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NUMCOMPTEUR {
            get {
                return this.NUMCOMPTEURField;
            }
            set {
                if ((object.ReferenceEquals(this.NUMCOMPTEURField, value) != true)) {
                    this.NUMCOMPTEURField = value;
                    this.RaisePropertyChanged("NUMCOMPTEUR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ORDRE {
            get {
                return this.ORDREField;
            }
            set {
                if ((object.ReferenceEquals(this.ORDREField, value) != true)) {
                    this.ORDREField = value;
                    this.RaisePropertyChanged("ORDRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OptionRecherche {
            get {
                return this.OptionRechercheField;
            }
            set {
                if ((this.OptionRechercheField.Equals(value) != true)) {
                    this.OptionRechercheField = value;
                    this.RaisePropertyChanged("OptionRecherche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERIODE {
            get {
                return this.PERIODEField;
            }
            set {
                if ((object.ReferenceEquals(this.PERIODEField, value) != true)) {
                    this.PERIODEField = value;
                    this.RaisePropertyChanged("PERIODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PK_ID {
            get {
                return this.PK_IDField;
            }
            set {
                if ((this.PK_IDField.Equals(value) != true)) {
                    this.PK_IDField = value;
                    this.RaisePropertyChanged("PK_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int POINT {
            get {
                return this.POINTField;
            }
            set {
                if ((this.POINTField.Equals(value) != true)) {
                    this.POINTField = value;
                    this.RaisePropertyChanged("POINT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PORTE {
            get {
                return this.PORTEField;
            }
            set {
                if ((object.ReferenceEquals(this.PORTEField, value) != true)) {
                    this.PORTEField = value;
                    this.RaisePropertyChanged("PORTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUIT {
            get {
                return this.PRODUITField;
            }
            set {
                if ((object.ReferenceEquals(this.PRODUITField, value) != true)) {
                    this.PRODUITField = value;
                    this.RaisePropertyChanged("PRODUIT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUE {
            get {
                return this.RUEField;
            }
            set {
                if ((object.ReferenceEquals(this.RUEField, value) != true)) {
                    this.RUEField = value;
                    this.RaisePropertyChanged("RUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SEQUENCE {
            get {
                return this.SEQUENCEField;
            }
            set {
                if ((object.ReferenceEquals(this.SEQUENCEField, value) != true)) {
                    this.SEQUENCEField = value;
                    this.RaisePropertyChanged("SEQUENCE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TOURNEE {
            get {
                return this.TOURNEEField;
            }
            set {
                if ((object.ReferenceEquals(this.TOURNEEField, value) != true)) {
                    this.TOURNEEField = value;
                    this.RaisePropertyChanged("TOURNEE");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CsAbonneCarte", Namespace="http://schemas.datacontract.org/2004/07/Galatee.Structure")]
    public partial class CsAbonneCarte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CentreField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string NomAbonneField;
        
        private string NumeroClientField;
        
        private string TelephoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Centre {
            get {
                return this.CentreField;
            }
            set {
                if ((object.ReferenceEquals(this.CentreField, value) != true)) {
                    this.CentreField = value;
                    this.RaisePropertyChanged("Centre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LatitudeField, value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((object.ReferenceEquals(this.LongitudeField, value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomAbonne {
            get {
                return this.NomAbonneField;
            }
            set {
                if ((object.ReferenceEquals(this.NomAbonneField, value) != true)) {
                    this.NomAbonneField = value;
                    this.RaisePropertyChanged("NomAbonne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroClient {
            get {
                return this.NumeroClientField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroClientField, value) != true)) {
                    this.NumeroClientField = value;
                    this.RaisePropertyChanged("NumeroClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSig.ISigService")]
    public interface ISigService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISigService/RetourneCoordonneesAbon", ReplyAction="http://tempuri.org/ISigService/RetourneCoordonneesAbonResponse")]
        System.IAsyncResult BeginRetourneCoordonneesAbon(Galatee.Silverlight.ServiceSig.CsClientRechercher client, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> EndRetourneCoordonneesAbon(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISigService/RetourneCoordonneesAbonCampagne", ReplyAction="http://tempuri.org/ISigService/RetourneCoordonneesAbonCampagneResponse")]
        System.IAsyncResult BeginRetourneCoordonneesAbonCampagne(string IdCoupure, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> EndRetourneCoordonneesAbonCampagne(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISigServiceChannel : Galatee.Silverlight.ServiceSig.ISigService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetourneCoordonneesAbonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetourneCoordonneesAbonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetourneCoordonneesAbonCampagneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetourneCoordonneesAbonCampagneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SigServiceClient : System.ServiceModel.ClientBase<Galatee.Silverlight.ServiceSig.ISigService>, Galatee.Silverlight.ServiceSig.ISigService {
        
        private BeginOperationDelegate onBeginRetourneCoordonneesAbonDelegate;
        
        private EndOperationDelegate onEndRetourneCoordonneesAbonDelegate;
        
        private System.Threading.SendOrPostCallback onRetourneCoordonneesAbonCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetourneCoordonneesAbonCampagneDelegate;
        
        private EndOperationDelegate onEndRetourneCoordonneesAbonCampagneDelegate;
        
        private System.Threading.SendOrPostCallback onRetourneCoordonneesAbonCampagneCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SigServiceClient() {
        }
        
        public SigServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SigServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SigServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SigServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RetourneCoordonneesAbonCompletedEventArgs> RetourneCoordonneesAbonCompleted;
        
        public event System.EventHandler<RetourneCoordonneesAbonCampagneCompletedEventArgs> RetourneCoordonneesAbonCampagneCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Galatee.Silverlight.ServiceSig.ISigService.BeginRetourneCoordonneesAbon(Galatee.Silverlight.ServiceSig.CsClientRechercher client, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetourneCoordonneesAbon(client, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> Galatee.Silverlight.ServiceSig.ISigService.EndRetourneCoordonneesAbon(System.IAsyncResult result) {
            return base.Channel.EndRetourneCoordonneesAbon(result);
        }
        
        private System.IAsyncResult OnBeginRetourneCoordonneesAbon(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Galatee.Silverlight.ServiceSig.CsClientRechercher client = ((Galatee.Silverlight.ServiceSig.CsClientRechercher)(inValues[0]));
            return ((Galatee.Silverlight.ServiceSig.ISigService)(this)).BeginRetourneCoordonneesAbon(client, callback, asyncState);
        }
        
        private object[] OnEndRetourneCoordonneesAbon(System.IAsyncResult result) {
            System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> retVal = ((Galatee.Silverlight.ServiceSig.ISigService)(this)).EndRetourneCoordonneesAbon(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetourneCoordonneesAbonCompleted(object state) {
            if ((this.RetourneCoordonneesAbonCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetourneCoordonneesAbonCompleted(this, new RetourneCoordonneesAbonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetourneCoordonneesAbonAsync(Galatee.Silverlight.ServiceSig.CsClientRechercher client) {
            this.RetourneCoordonneesAbonAsync(client, null);
        }
        
        public void RetourneCoordonneesAbonAsync(Galatee.Silverlight.ServiceSig.CsClientRechercher client, object userState) {
            if ((this.onBeginRetourneCoordonneesAbonDelegate == null)) {
                this.onBeginRetourneCoordonneesAbonDelegate = new BeginOperationDelegate(this.OnBeginRetourneCoordonneesAbon);
            }
            if ((this.onEndRetourneCoordonneesAbonDelegate == null)) {
                this.onEndRetourneCoordonneesAbonDelegate = new EndOperationDelegate(this.OnEndRetourneCoordonneesAbon);
            }
            if ((this.onRetourneCoordonneesAbonCompletedDelegate == null)) {
                this.onRetourneCoordonneesAbonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetourneCoordonneesAbonCompleted);
            }
            base.InvokeAsync(this.onBeginRetourneCoordonneesAbonDelegate, new object[] {
                        client}, this.onEndRetourneCoordonneesAbonDelegate, this.onRetourneCoordonneesAbonCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Galatee.Silverlight.ServiceSig.ISigService.BeginRetourneCoordonneesAbonCampagne(string IdCoupure, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetourneCoordonneesAbonCampagne(IdCoupure, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> Galatee.Silverlight.ServiceSig.ISigService.EndRetourneCoordonneesAbonCampagne(System.IAsyncResult result) {
            return base.Channel.EndRetourneCoordonneesAbonCampagne(result);
        }
        
        private System.IAsyncResult OnBeginRetourneCoordonneesAbonCampagne(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string IdCoupure = ((string)(inValues[0]));
            return ((Galatee.Silverlight.ServiceSig.ISigService)(this)).BeginRetourneCoordonneesAbonCampagne(IdCoupure, callback, asyncState);
        }
        
        private object[] OnEndRetourneCoordonneesAbonCampagne(System.IAsyncResult result) {
            System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> retVal = ((Galatee.Silverlight.ServiceSig.ISigService)(this)).EndRetourneCoordonneesAbonCampagne(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetourneCoordonneesAbonCampagneCompleted(object state) {
            if ((this.RetourneCoordonneesAbonCampagneCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetourneCoordonneesAbonCampagneCompleted(this, new RetourneCoordonneesAbonCampagneCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetourneCoordonneesAbonCampagneAsync(string IdCoupure) {
            this.RetourneCoordonneesAbonCampagneAsync(IdCoupure, null);
        }
        
        public void RetourneCoordonneesAbonCampagneAsync(string IdCoupure, object userState) {
            if ((this.onBeginRetourneCoordonneesAbonCampagneDelegate == null)) {
                this.onBeginRetourneCoordonneesAbonCampagneDelegate = new BeginOperationDelegate(this.OnBeginRetourneCoordonneesAbonCampagne);
            }
            if ((this.onEndRetourneCoordonneesAbonCampagneDelegate == null)) {
                this.onEndRetourneCoordonneesAbonCampagneDelegate = new EndOperationDelegate(this.OnEndRetourneCoordonneesAbonCampagne);
            }
            if ((this.onRetourneCoordonneesAbonCampagneCompletedDelegate == null)) {
                this.onRetourneCoordonneesAbonCampagneCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetourneCoordonneesAbonCampagneCompleted);
            }
            base.InvokeAsync(this.onBeginRetourneCoordonneesAbonCampagneDelegate, new object[] {
                        IdCoupure}, this.onEndRetourneCoordonneesAbonCampagneDelegate, this.onRetourneCoordonneesAbonCampagneCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Galatee.Silverlight.ServiceSig.ISigService CreateChannel() {
            return new SigServiceClientChannel(this);
        }
        
        private class SigServiceClientChannel : ChannelBase<Galatee.Silverlight.ServiceSig.ISigService>, Galatee.Silverlight.ServiceSig.ISigService {
            
            public SigServiceClientChannel(System.ServiceModel.ClientBase<Galatee.Silverlight.ServiceSig.ISigService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRetourneCoordonneesAbon(Galatee.Silverlight.ServiceSig.CsClientRechercher client, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = client;
                System.IAsyncResult _result = base.BeginInvoke("RetourneCoordonneesAbon", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> EndRetourneCoordonneesAbon(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> _result = ((System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte>)(base.EndInvoke("RetourneCoordonneesAbon", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetourneCoordonneesAbonCampagne(string IdCoupure, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = IdCoupure;
                System.IAsyncResult _result = base.BeginInvoke("RetourneCoordonneesAbonCampagne", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> EndRetourneCoordonneesAbonCampagne(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte> _result = ((System.Collections.Generic.List<Galatee.Silverlight.ServiceSig.CsAbonneCarte>)(base.EndInvoke("RetourneCoordonneesAbonCampagne", _args, result)));
                return _result;
            }
        }
    }
}
