//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Silverlight.Resources.Devis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galatee.Silverlight.Resources.Devis.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accompte.
        /// </summary>
        internal static string Accompte {
            get {
                return ResourceManager.GetString("Accompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à corriger.
        /// </summary>
        internal static string aCorriger {
            get {
                return ResourceManager.GetString("aCorriger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administracion.
        /// </summary>
        internal static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payeur.
        /// </summary>
        internal static string Applicant {
            get {
                return ResourceManager.GetString("Applicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun acompte trouvé.
        /// </summary>
        internal static string AucunAccompteTrouve {
            get {
                return ResourceManager.GetString("AucunAccompteTrouve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune donnée trouvée.
        /// </summary>
        internal static string AucunesDonneesTrouvees {
            get {
                return ResourceManager.GetString("AucunesDonneesTrouvees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorisation scannée.
        /// </summary>
        internal static string AutorisationScannee {
            get {
                return ResourceManager.GetString("AutorisationScannee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resiliation.
        /// </summary>
        internal static string Btn_reset {
            get {
                return ResourceManager.GetString("Btn_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        internal static string Btn_search {
            get {
                return ResourceManager.GetString("Btn_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmettre.
        /// </summary>
        internal static string Btn_Transmettre {
            get {
                return ResourceManager.GetString("Btn_Transmettre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifier.
        /// </summary>
        internal static string Btn_Verifier {
            get {
                return ResourceManager.GetString("Btn_Verifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        internal static string btnAide {
            get {
                return ResourceManager.GetString("btnAide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        internal static string btnAjouter {
            get {
                return ResourceManager.GetString("btnAjouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string btnAnnuler {
            get {
                return ResourceManager.GetString("btnAnnuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;  Avancée.
        /// </summary>
        internal static string btnAvancee {
            get {
                return ResourceManager.GetString("btnAvancee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clôturer.
        /// </summary>
        internal static string btnCloturer {
            get {
                return ResourceManager.GetString("btnCloturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commenter.
        /// </summary>
        internal static string btnCommenter {
            get {
                return ResourceManager.GetString("btnCommenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulter.
        /// </summary>
        internal static string btnConsulter {
            get {
                return ResourceManager.GetString("btnConsulter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        internal static string btnCreer {
            get {
                return ResourceManager.GetString("btnCreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string btnDetails {
            get {
                return ResourceManager.GetString("btnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        internal static string btnEditer {
            get {
                return ResourceManager.GetString("btnEditer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string btnEnregistrer {
            get {
                return ResourceManager.GetString("btnEnregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablir.
        /// </summary>
        internal static string btnEtablir {
            get {
                return ResourceManager.GetString("btnEtablir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string btnFermer {
            get {
                return ResourceManager.GetString("btnFermer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string btnModifier {
            get {
                return ResourceManager.GetString("btnModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent.
        /// </summary>
        internal static string btnPrecedent {
            get {
                return ResourceManager.GetString("btnPrecedent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        internal static string btnRechercher {
            get {
                return ResourceManager.GetString("btnRechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réinitialiser.
        /// </summary>
        internal static string btnReinitialiser {
            get {
                return ResourceManager.GetString("btnReinitialiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejeter.
        /// </summary>
        internal static string btnRejeter {
            get {
                return ResourceManager.GetString("btnRejeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        internal static string btnSuivant {
            get {
                return ResourceManager.GetString("btnSuivant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string btnSupprimer {
            get {
                return ResourceManager.GetString("btnSupprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmettre.
        /// </summary>
        internal static string btnTransmettre {
            get {
                return ResourceManager.GetString("btnTransmettre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        internal static string btnValider {
            get {
                return ResourceManager.GetString("btnValider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string centre {
            get {
                return ResourceManager.GetString("centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifiable.
        /// </summary>
        internal static string ckbIdentifiable {
            get {
                return ResourceManager.GetString("ckbIdentifiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acompte non nécessaire.
        /// </summary>
        internal static string ckbNoDeposit {
            get {
                return ResourceManager.GetString("ckbNoDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string columnHeaderCentre {
            get {
                return ResourceManager.GetString("columnHeaderCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Annulation.
        /// </summary>
        internal static string columnHeaderDateAnnulation {
            get {
                return ResourceManager.GetString("columnHeaderDateAnnulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date création.
        /// </summary>
        internal static string columnHeaderDateCreation {
            get {
                return ResourceManager.GetString("columnHeaderDateCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date limite.
        /// </summary>
        internal static string columnHeaderDateLimite {
            get {
                return ResourceManager.GetString("columnHeaderDateLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape.
        /// </summary>
        internal static string columnHeaderEtape {
            get {
                return ResourceManager.GetString("columnHeaderEtape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etat.
        /// </summary>
        internal static string columnHeaderEtat {
            get {
                return ResourceManager.GetString("columnHeaderEtat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonction.
        /// </summary>
        internal static string columnHeaderFonction {
            get {
                return ResourceManager.GetString("columnHeaderFonction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° devis.
        /// </summary>
        internal static string columnHeaderNumDevis {
            get {
                return ResourceManager.GetString("columnHeaderNumDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origine.
        /// </summary>
        internal static string columnHeaderOrigine {
            get {
                return ResourceManager.GetString("columnHeaderOrigine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit.
        /// </summary>
        internal static string columnHeaderProduit {
            get {
                return ResourceManager.GetString("columnHeaderProduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps Execution.
        /// </summary>
        internal static string columnHeaderTempsExecution {
            get {
                return ResourceManager.GetString("columnHeaderTempsExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type devis.
        /// </summary>
        internal static string columnHeaderTypeDevis {
            get {
                return ResourceManager.GetString("columnHeaderTypeDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veillez patienter pendant le chargement de data .....
        /// </summary>
        internal static string Data_Loading {
            get {
                return ResourceManager.GetString("Data_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Accompte.
        /// </summary>
        internal static string DateAccompte {
            get {
                return ResourceManager.GetString("DateAccompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce reçu a déjà été utilisé par la demande {0}..
        /// </summary>
        internal static string DepositHasBeenUsed {
            get {
                return ResourceManager.GetString("DepositHasBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce reçu n&apos;existe pas..
        /// </summary>
        internal static string DepositNotExist {
            get {
                return ResourceManager.GetString("DepositNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to établi.
        /// </summary>
        internal static string etatEtabli {
            get {
                return ResourceManager.GetString("etatEtabli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initié.
        /// </summary>
        internal static string etatInitie {
            get {
                return ResourceManager.GetString("etatInitie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonction.
        /// </summary>
        internal static string fonction {
            get {
                return ResourceManager.GetString("fonction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appareils et foyers lunmineux.
        /// </summary>
        internal static string gboAppareilsFoyers {
            get {
                return ResourceManager.GetString("gboAppareilsFoyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres Informations.
        /// </summary>
        internal static string gboAutresInformations {
            get {
                return ResourceManager.GetString("gboAutresInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilan.
        /// </summary>
        internal static string gboBilanDevis {
            get {
                return ResourceManager.GetString("gboBilanDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caractéristiques.
        /// </summary>
        internal static string gboCaracteristiques {
            get {
                return ResourceManager.GetString("gboCaracteristiques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails appareil.
        /// </summary>
        internal static string gboDetailsAppareil {
            get {
                return ResourceManager.GetString("gboDetailsAppareil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elément du devis : Fournitures.
        /// </summary>
        internal static string gboElementDevis {
            get {
                return ResourceManager.GetString("gboElementDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string gboInformation {
            get {
                return ResourceManager.GetString("gboInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations du demandeur.
        /// </summary>
        internal static string gboInformationDemandeur {
            get {
                return ResourceManager.GetString("gboInformationDemandeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation.
        /// </summary>
        internal static string gboInformationLocalisation {
            get {
                return ResourceManager.GetString("gboInformationLocalisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Recherche avancée .
        /// </summary>
        internal static string gboRechercheAvancee {
            get {
                return ResourceManager.GetString("gboRechercheAvancee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Résultats de la recherche .
        /// </summary>
        internal static string gboResultatRecherche {
            get {
                return ResourceManager.GetString("gboResultatRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string lbl_Client {
            get {
                return ResourceManager.GetString("lbl_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant à rembourser.
        /// </summary>
        internal static string lbl_MontantARembourser {
            get {
                return ResourceManager.GetString("lbl_MontantARembourser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motif de l&apos;annulation.
        /// </summary>
        internal static string lbl_Motif {
            get {
                return ResourceManager.GetString("lbl_Motif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom agent.
        /// </summary>
        internal static string lbl_NomAgent {
            get {
                return ResourceManager.GetString("lbl_NomAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string lbl_Sequence {
            get {
                return ResourceManager.GetString("lbl_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type de devis.
        /// </summary>
        internal static string lbl_TypeDevis {
            get {
                return ResourceManager.GetString("lbl_TypeDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acteur étape.
        /// </summary>
        internal static string lblActeurEtape {
            get {
                return ResourceManager.GetString("lblActeurEtape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autres informations.
        /// </summary>
        internal static string lblAutresInformations {
            get {
                return ResourceManager.GetString("lblAutresInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibre.
        /// </summary>
        internal static string lblCalibre {
            get {
                return ResourceManager.GetString("lblCalibre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string lblCentre {
            get {
                return ResourceManager.GetString("lblCentre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélection chef d&apos;équipe travaux.
        /// </summary>
        internal static string lblChefEquipe {
            get {
                return ResourceManager.GetString("lblChefEquipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code appareil.
        /// </summary>
        internal static string lblCodeAppareil {
            get {
                return ResourceManager.GetString("lblCodeAppareil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commune.
        /// </summary>
        internal static string lblCommune {
            get {
                return ResourceManager.GetString("lblCommune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string lblConformationPwd {
            get {
                return ResourceManager.GetString("lblConformationPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cout Total.
        /// </summary>
        internal static string lblCoutTotal {
            get {
                return ResourceManager.GetString("lblCoutTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date limite.
        /// </summary>
        internal static string lblDateLimite {
            get {
                return ResourceManager.GetString("lblDateLimite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désignation.
        /// </summary>
        internal static string lblDesignation {
            get {
                return ResourceManager.GetString("lblDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails du devis.
        /// </summary>
        internal static string lblDetailsDevis {
            get {
                return ResourceManager.GetString("lblDetailsDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape.
        /// </summary>
        internal static string lblEtape {
            get {
                return ResourceManager.GetString("lblEtape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape de rejet.
        /// </summary>
        internal static string lblEtapeRejet {
            get {
                return ResourceManager.GetString("lblEtapeRejet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis.
        /// </summary>
        internal static string lblGestionDeDevis {
            get {
                return ResourceManager.GetString("lblGestionDeDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro GPS.
        /// </summary>
        internal static string lblGPS {
            get {
                return ResourceManager.GetString("lblGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricule.
        /// </summary>
        internal static string lblMatricule {
            get {
                return ResourceManager.GetString("lblMatricule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant.
        /// </summary>
        internal static string lblMontant {
            get {
                return ResourceManager.GetString("lblMontant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant HT.
        /// </summary>
        internal static string lblMontantHT {
            get {
                return ResourceManager.GetString("lblMontantHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant TTC.
        /// </summary>
        internal static string lblMontantTTC {
            get {
                return ResourceManager.GetString("lblMontantTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant TVA.
        /// </summary>
        internal static string lblMontantTVA {
            get {
                return ResourceManager.GetString("lblMontantTVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motif du rejet.
        /// </summary>
        internal static string lblMotifRejet {
            get {
                return ResourceManager.GetString("lblMotifRejet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string lblNom {
            get {
                return ResourceManager.GetString("lblNom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string lblNom2 {
            get {
                return ResourceManager.GetString("lblNom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string lblNombre {
            get {
                return ResourceManager.GetString("lblNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du produit.
        /// </summary>
        internal static string lblNomProduit {
            get {
                return ResourceManager.GetString("lblNomProduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la société.
        /// </summary>
        internal static string lblNomSociete {
            get {
                return ResourceManager.GetString("lblNomSociete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau mot de passe.
        /// </summary>
        internal static string lblNouveauPwd {
            get {
                return ResourceManager.GetString("lblNouveauPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        internal static string lblNumero {
            get {
                return ResourceManager.GetString("lblNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro du devis .
        /// </summary>
        internal static string lblNumeroDuDevis {
            get {
                return ResourceManager.GetString("lblNumeroDuDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro du lot.
        /// </summary>
        internal static string lblNumeroLot {
            get {
                return ResourceManager.GetString("lblNumeroLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro pièce.
        /// </summary>
        internal static string lblNumeroPiece {
            get {
                return ResourceManager.GetString("lblNumeroPiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de porte.
        /// </summary>
        internal static string lblNumeroPorte {
            get {
                return ResourceManager.GetString("lblNumeroPorte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de rue.
        /// </summary>
        internal static string lblNumeroRue {
            get {
                return ResourceManager.GetString("lblNumeroRue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcelle.
        /// </summary>
        internal static string lblParcelle {
            get {
                return ResourceManager.GetString("lblParcelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poteau.
        /// </summary>
        internal static string lblPoteau {
            get {
                return ResourceManager.GetString("lblPoteau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poteau le plus proche.
        /// </summary>
        internal static string lblPoteauProche {
            get {
                return ResourceManager.GetString("lblPoteauProche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénoms.
        /// </summary>
        internal static string lblPrenoms {
            get {
                return ResourceManager.GetString("lblPrenoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prix Unitaire.
        /// </summary>
        internal static string lblPrixUnitaire {
            get {
                return ResourceManager.GetString("lblPrixUnitaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produit.
        /// </summary>
        internal static string lblProduit {
            get {
                return ResourceManager.GetString("lblProduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string lblProfession {
            get {
                return ResourceManager.GetString("lblProfession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preuve propriété.
        /// </summary>
        internal static string lblPropriete {
            get {
                return ResourceManager.GetString("lblPropriete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puissance.
        /// </summary>
        internal static string lblPuissance {
            get {
                return ResourceManager.GetString("lblPuissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantité.
        /// </summary>
        internal static string lblQuantite {
            get {
                return ResourceManager.GetString("lblQuantite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartier.
        /// </summary>
        internal static string lblQuartier {
            get {
                return ResourceManager.GetString("lblQuartier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repère le plus proche.
        /// </summary>
        internal static string lblRepereProche {
            get {
                return ResourceManager.GetString("lblRepereProche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secteur.
        /// </summary>
        internal static string lblSecteur {
            get {
                return ResourceManager.GetString("lblSecteur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string lblSection {
            get {
                return ResourceManager.GetString("lblSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Téléphone.
        /// </summary>
        internal static string lblTelephone {
            get {
                return ResourceManager.GetString("lblTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tension.
        /// </summary>
        internal static string lblTension {
            get {
                return ResourceManager.GetString("lblTension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant total.
        /// </summary>
        internal static string lblTotalMontant {
            get {
                return ResourceManager.GetString("lblTotalMontant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournée.
        /// </summary>
        internal static string lblTournee {
            get {
                return ResourceManager.GetString("lblTournee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TTC.
        /// </summary>
        internal static string lblTTC {
            get {
                return ResourceManager.GetString("lblTTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pièce d&apos;identité.
        /// </summary>
        internal static string lblTypePiece {
            get {
                return ResourceManager.GetString("lblTypePiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur.
        /// </summary>
        internal static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisé.
        /// </summary>
        internal static string lblUtilise {
            get {
                return ResourceManager.GetString("lblUtilise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter l&apos;autorisation scannée.
        /// </summary>
        internal static string lnkLetter {
            get {
                return ResourceManager.GetString("lnkLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        internal static string mnuAccueil {
            get {
                return ResourceManager.GetString("mnuAccueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propos de.
        /// </summary>
        internal static string mnuAPropos {
            get {
                return ResourceManager.GetString("mnuAPropos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon de contrôle.
        /// </summary>
        internal static string mnuBonControle {
            get {
                return ResourceManager.GetString("mnuBonControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon de sortie matériel.
        /// </summary>
        internal static string mnuBonDeSortie {
            get {
                return ResourceManager.GetString("mnuBonDeSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon de remboursement.
        /// </summary>
        internal static string mnuBonRemboursement {
            get {
                return ResourceManager.GetString("mnuBonRemboursement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon retour matériel.
        /// </summary>
        internal static string mnuBonRetourMateriel {
            get {
                return ResourceManager.GetString("mnuBonRetourMateriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon travaux.
        /// </summary>
        internal static string mnuBonTravaux {
            get {
                return ResourceManager.GetString("mnuBonTravaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clôture des dossiers.
        /// </summary>
        internal static string mnuClotureDesDossiers {
            get {
                return ResourceManager.GetString("mnuClotureDesDossiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation des devis.
        /// </summary>
        internal static string mnuConsultationDesDevis {
            get {
                return ResourceManager.GetString("mnuConsultationDesDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devis.
        /// </summary>
        internal static string mnuDevis {
            get {
                return ResourceManager.GetString("mnuDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devis à encaisser.
        /// </summary>
        internal static string mnuDevisAEncaisser {
            get {
                return ResourceManager.GetString("mnuDevisAEncaisser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devis clôturés.
        /// </summary>
        internal static string mnuDevisClotures {
            get {
                return ResourceManager.GetString("mnuDevisClotures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devis dans le circuit.
        /// </summary>
        internal static string mnuDevisNonClotures {
            get {
                return ResourceManager.GetString("mnuDevisNonClotures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editions.
        /// </summary>
        internal static string mnuEdition {
            get {
                return ResourceManager.GetString("mnuEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etablissement devis.
        /// </summary>
        internal static string mnuEtablissementDevis {
            get {
                return ResourceManager.GetString("mnuEtablissementDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etapes devis.
        /// </summary>
        internal static string mnuEtapesDevis {
            get {
                return ResourceManager.GetString("mnuEtapesDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer la session.
        /// </summary>
        internal static string mnuFermerSession {
            get {
                return ResourceManager.GetString("mnuFermerSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        internal static string mnuFichier {
            get {
                return ResourceManager.GetString("mnuFichier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procès verbal.
        /// </summary>
        internal static string mnuProcesVerbal {
            get {
                return ResourceManager.GetString("mnuProcesVerbal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        internal static string mnuQuitter {
            get {
                return ResourceManager.GetString("mnuQuitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport de contrôle.
        /// </summary>
        internal static string mnuRapportControle {
            get {
                return ResourceManager.GetString("mnuRapportControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reédition.
        /// </summary>
        internal static string mnuReedition {
            get {
                return ResourceManager.GetString("mnuReedition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation devis.
        /// </summary>
        internal static string mnuValidationDevis {
            get {
                return ResourceManager.GetString("mnuValidationDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montant Accompte.
        /// </summary>
        internal static string MontantAccompte {
            get {
                return ResourceManager.GetString("MontantAccompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez ajouter des éléments avant de poursuivre.
        /// </summary>
        internal static string msgAddFournitures {
            get {
                return ResourceManager.GetString("msgAddFournitures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation erronée.
        /// </summary>
        internal static string msgBadPwd {
            get {
                return ResourceManager.GetString("msgBadPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue.
        /// </summary>
        internal static string msgBienvenue {
            get {
                return ResourceManager.GetString("msgBienvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape &quot;Etablissement bon de sortie&quot; non encore exécutée.
        /// </summary>
        internal static string msgBonSortieNonEtabli {
            get {
                return ResourceManager.GetString("msgBonSortieNonEtabli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez spécifier un chef d&apos;équipe travaux pour poursuivre.
        /// </summary>
        internal static string msgChoixChefEquipe {
            get {
                return ResourceManager.GetString("msgChoixChefEquipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validez vous les informations entrées?.
        /// </summary>
        internal static string msgConfirmControle {
            get {
                return ResourceManager.GetString("msgConfirmControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirmez-vous le rejet de ce devis?.
        /// </summary>
        internal static string msgConfirmRejection {
            get {
                return ResourceManager.GetString("msgConfirmRejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez-vous le retour en stock de ce matériel?.
        /// </summary>
        internal static string msgConfirmRemisStock {
            get {
                return ResourceManager.GetString("msgConfirmRemisStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez-vous la suppression de cet élément?.
        /// </summary>
        internal static string msgConfirmSuppression {
            get {
                return ResourceManager.GetString("msgConfirmSuppression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous transmettre le devis?.
        /// </summary>
        internal static string msgConfirmTransmit {
            get {
                return ResourceManager.GetString("msgConfirmTransmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmez-vous la validation de ce devis?.
        /// </summary>
        internal static string msgConfirmValidation {
            get {
                return ResourceManager.GetString("msgConfirmValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape &quot;Contrôle des travaux&quot; non exécutée.
        /// </summary>
        internal static string msgControleNonFait {
            get {
                return ResourceManager.GetString("msgControleNonFait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape &quot;Décision contrôle&quot; non encore exécutée.
        /// </summary>
        internal static string msgDecisionControleNonFaite {
            get {
                return ResourceManager.GetString("msgDecisionControleNonFaite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dossier non enocre clôturé.
        /// </summary>
        internal static string msgDevisNonCloturé {
            get {
                return ResourceManager.GetString("msgDevisNonCloturé", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chef d&apos;équipe travaux inexistant.
        /// </summary>
        internal static string msgEmptyChefEquipe {
            get {
                return ResourceManager.GetString("msgEmptyChefEquipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez d&apos;abord saisir un numéro de devis....
        /// </summary>
        internal static string msgEmptyDevis {
            get {
                return ResourceManager.GetString("msgEmptyDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements du devis non fournis.
        /// </summary>
        internal static string msgEmptyFournitures {
            get {
                return ResourceManager.GetString("msgEmptyFournitures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pas de devis à traiter.
        /// </summary>
        internal static string msgEmptyListeDevis {
            get {
                return ResourceManager.GetString("msgEmptyListeDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez saisir un matricule et un mot de passe.
        /// </summary>
        internal static string msgEmptyLogin {
            get {
                return ResourceManager.GetString("msgEmptyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez saisir un matricule.
        /// </summary>
        internal static string msgEmptyMatricule {
            get {
                return ResourceManager.GetString("msgEmptyMatricule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez saisir un mot de passe.
        /// </summary>
        internal static string msgEmptyPassword {
            get {
                return ResourceManager.GetString("msgEmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun traitement en attente.
        /// </summary>
        internal static string msgEmptyProcess {
            get {
                return ResourceManager.GetString("msgEmptyProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun matériel n&apos;a été remis en stock.
        /// </summary>
        internal static string msgEmptyRemisStock {
            get {
                return ResourceManager.GetString("msgEmptyRemisStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez selectionner un agent.
        /// </summary>
        internal static string msgEmptyUser {
            get {
                return ResourceManager.GetString("msgEmptyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors du chargement des données.
        /// </summary>
        internal static string msgErreurChargementDonnees {
            get {
                return ResourceManager.GetString("msgErreurChargementDonnees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la création du devis.
        /// </summary>
        internal static string msgErreurCreationDevis {
            get {
                return ResourceManager.GetString("msgErreurCreationDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de l&apos;impression !.
        /// </summary>
        internal static string msgErreurImpression {
            get {
                return ResourceManager.GetString("msgErreurImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la mise à jour du devis.
        /// </summary>
        internal static string msgErreurMiseAJourDevis {
            get {
                return ResourceManager.GetString("msgErreurMiseAJourDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonction de l&apos;agent non identifiée.
        /// </summary>
        internal static string msgFonctionAgentNonIdentifie {
            get {
                return ResourceManager.GetString("msgFonctionAgentNonIdentifie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur authentifié.
        /// </summary>
        internal static string msgLoginOk {
            get {
                return ResourceManager.GetString("msgLoginOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre supérieur à la quantité initiale .
        /// </summary>
        internal static string msgMauvaiseQuantiteRetour {
            get {
                return ResourceManager.GetString("msgMauvaiseQuantiteRetour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Effectué avec succès.
        /// </summary>
        internal static string msgOperationEffectueAvecSucces {
            get {
                return ResourceManager.GetString("msgOperationEffectueAvecSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le devis {0} est à l&apos;ordre {1}.
        /// </summary>
        internal static string msgOrdreDuDevis {
            get {
                return ResourceManager.GetString("msgOrdreDuDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe incorrect.
        /// </summary>
        internal static string msgPasswordInconnu {
            get {
                return ResourceManager.GetString("msgPasswordInconnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etape &quot;Etablissement procès verbal&quot; non encore exécutée.
        /// </summary>
        internal static string msgProcesVerbalNonEtabli {
            get {
                return ResourceManager.GetString("msgProcesVerbalNonEtabli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous quitter l&apos;application?.
        /// </summary>
        internal static string msgQuitter {
            get {
                return ResourceManager.GetString("msgQuitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devis introuvable.
        /// </summary>
        internal static string msgRequestNotFound {
            get {
                return ResourceManager.GetString("msgRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous fermer cette session?.
        /// </summary>
        internal static string msgRestart {
            get {
                return ResourceManager.GetString("msgRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateur Inconnu.
        /// </summary>
        internal static string msgUserInconnu {
            get {
                return ResourceManager.GetString("msgUserInconnu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation de l&apos;utilisateur.
        /// </summary>
        internal static string msgUserValidation {
            get {
                return ResourceManager.GetString("msgUserValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devis non encore validé.
        /// </summary>
        internal static string msgValidationNonFaite {
            get {
                return ResourceManager.GetString("msgValidationNonFaite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez saisir un nombre s&apos;il vous plaît !.
        /// </summary>
        internal static string msgVerificationNombre {
            get {
                return ResourceManager.GetString("msgVerificationNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de reçu.
        /// </summary>
        internal static string NumeroRecu {
            get {
                return ResourceManager.GetString("NumeroRecu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to création.
        /// </summary>
        internal static string origineCreation {
            get {
                return ResourceManager.GetString("origineCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rejet.
        /// </summary>
        internal static string origineRejet {
            get {
                return ResourceManager.GetString("origineRejet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénoms.
        /// </summary>
        internal static string Prenoms {
            get {
                return ResourceManager.GetString("Prenoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recherche.
        /// </summary>
        internal static string recherche {
            get {
                return ResourceManager.GetString("recherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinitialiser.
        /// </summary>
        internal static string reinitialiser {
            get {
                return ResourceManager.GetString("reinitialiser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilan.
        /// </summary>
        internal static string RptBilan {
            get {
                return ResourceManager.GetString("RptBilan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonControle.
        /// </summary>
        internal static string RptBonControl {
            get {
                return ResourceManager.GetString("RptBonControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonDeControle.
        /// </summary>
        internal static string RptBonDeControle {
            get {
                return ResourceManager.GetString("RptBonDeControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonDeSortie.
        /// </summary>
        internal static string RptBonDeSortie {
            get {
                return ResourceManager.GetString("RptBonDeSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonEntreeStock.
        /// </summary>
        internal static string RptBonEntreeStock {
            get {
                return ResourceManager.GetString("RptBonEntreeStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BonTravaux.
        /// </summary>
        internal static string RptBonTravaux {
            get {
                return ResourceManager.GetString("RptBonTravaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devis.
        /// </summary>
        internal static string RptDevis {
            get {
                return ResourceManager.GetString("RptDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevisSeparation.
        /// </summary>
        internal static string RptDevisSeparation {
            get {
                return ResourceManager.GetString("RptDevisSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevisSubvention.
        /// </summary>
        internal static string RptDevisSubvention {
            get {
                return ResourceManager.GetString("RptDevisSubvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcesVerbal.
        /// </summary>
        internal static string RptProcesVerbal {
            get {
                return ResourceManager.GetString("RptProcesVerbal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilan.
        /// </summary>
        internal static string RptRapportBilan {
            get {
                return ResourceManager.GetString("RptRapportBilan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RapportControle.
        /// </summary>
        internal static string RptRapportControle {
            get {
                return ResourceManager.GetString("RptRapportControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un devis.
        /// </summary>
        internal static string tslRechercherDevis {
            get {
                return ResourceManager.GetString("tslRechercherDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Accueil].
        /// </summary>
        internal static string ttlAccueil {
            get {
                return ResourceManager.GetString("ttlAccueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentification.
        /// </summary>
        internal static string ttlAuthentification {
            get {
                return ResourceManager.GetString("ttlAuthentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Etablissement bon de sortie].
        /// </summary>
        internal static string ttlBonSortie {
            get {
                return ResourceManager.GetString("ttlBonSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification mot de passe.
        /// </summary>
        internal static string ttlChangementPwd {
            get {
                return ResourceManager.GetString("ttlChangementPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Clôture des dossiers].
        /// </summary>
        internal static string ttlClotureDossier {
            get {
                return ResourceManager.GetString("ttlClotureDossier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation d&apos;un devis.
        /// </summary>
        internal static string ttlConsultationUnDevis {
            get {
                return ResourceManager.GetString("ttlConsultationUnDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Liste des devis à controler].
        /// </summary>
        internal static string ttlControle {
            get {
                return ResourceManager.GetString("ttlControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création du devis.
        /// </summary>
        internal static string ttlCreationDevis {
            get {
                return ResourceManager.GetString("ttlCreationDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Décision de contrôle].
        /// </summary>
        internal static string ttlDecision {
            get {
                return ResourceManager.GetString("ttlDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de la demande.
        /// </summary>
        internal static string ttlDetailDemandeur {
            get {
                return ResourceManager.GetString("ttlDetailDemandeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection des éléments du devis.
        /// </summary>
        internal static string ttlDetailDevis {
            get {
                return ResourceManager.GetString("ttlDetailDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Liste des devis à encaisser].
        /// </summary>
        internal static string ttlDevisAEncaisser {
            get {
                return ResourceManager.GetString("ttlDevisAEncaisser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Liste des dossiers clôturés].
        /// </summary>
        internal static string ttlDossierCloture {
            get {
                return ResourceManager.GetString("ttlDossierCloture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Liste des dossiers non clôturés].
        /// </summary>
        internal static string ttlDossierNonCloture {
            get {
                return ResourceManager.GetString("ttlDossierNonCloture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Etablissement devis].
        /// </summary>
        internal static string ttlEtablissement {
            get {
                return ResourceManager.GetString("ttlEtablissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des Appareils et foyers lumineux installés.
        /// </summary>
        internal static string ttlListeAppareils {
            get {
                return ResourceManager.GetString("ttlListeAppareils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisie du procès verbal.
        /// </summary>
        internal static string ttlProcesVerbal {
            get {
                return ResourceManager.GetString("ttlProcesVerbal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Etablissement procès verbal].
        /// </summary>
        internal static string ttlPV {
            get {
                return ResourceManager.GetString("ttlPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récapitulatif du devis.
        /// </summary>
        internal static string ttlRecapitulatifDevis {
            get {
                return ResourceManager.GetString("ttlRecapitulatifDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Re-édition bon de contrôle].
        /// </summary>
        internal static string ttlReeditionBonControle {
            get {
                return ResourceManager.GetString("ttlReeditionBonControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Re-édition bon de remboursement].
        /// </summary>
        internal static string ttlReeditionBonRemboursement {
            get {
                return ResourceManager.GetString("ttlReeditionBonRemboursement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Re-édition bon retour matériel].
        /// </summary>
        internal static string ttlReeditionBonRetourMateriel {
            get {
                return ResourceManager.GetString("ttlReeditionBonRetourMateriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Re-édition bon de sortie].
        /// </summary>
        internal static string ttlReeditionBonSortie {
            get {
                return ResourceManager.GetString("ttlReeditionBonSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Re-édition bon travaux].
        /// </summary>
        internal static string ttlReeditionBonTravaux {
            get {
                return ResourceManager.GetString("ttlReeditionBonTravaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Re-édition devis].
        /// </summary>
        internal static string ttlReeditionDevis {
            get {
                return ResourceManager.GetString("ttlReeditionDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Re-édition procès verbal].
        /// </summary>
        internal static string ttlReeditionProcesVerbal {
            get {
                return ResourceManager.GetString("ttlReeditionProcesVerbal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Re-édition rapport de contrôle].
        /// </summary>
        internal static string ttlReeditionRapportControle {
            get {
                return ResourceManager.GetString("ttlReeditionRapportControle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motif rejet du devis.
        /// </summary>
        internal static string ttlRejetDevis {
            get {
                return ResourceManager.GetString("ttlRejetDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisir le numéro du devis.
        /// </summary>
        internal static string ttlSaisirDevis {
            get {
                return ResourceManager.GetString("ttlSaisirDevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Validation devis].
        /// </summary>
        internal static string ttlValidation {
            get {
                return ResourceManager.GetString("ttlValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestion de devis - [Validation du rapport de contrôle].
        /// </summary>
        internal static string ttlValidationcontrole {
            get {
                return ResourceManager.GetString("ttlValidationcontrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A modifier à l&apos;étape suivante.
        /// </summary>
        internal static string txtAModifier {
            get {
                return ResourceManager.GetString("txtAModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appareils.
        /// </summary>
        internal static string txtAppareils {
            get {
                return ResourceManager.GetString("txtAppareils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandeur.
        /// </summary>
        internal static string txtDemandeur {
            get {
                return ResourceManager.GetString("txtDemandeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce module permet la gestion du devis depuis sa  demande jusqu&apos;à sa clôture en passant par son établissement, sa validation et son encaissement....
        /// </summary>
        internal static string txtDescriptionProduit {
            get {
                return ResourceManager.GetString("txtDescriptionProduit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devis.
        /// </summary>
        internal static string txtDevis {
            get {
                return ResourceManager.GetString("txtDevis", resourceCulture);
            }
        }
    }
}
