//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABO07Entities : DbContext
    {
        public ABO07Entities()
            : base("name=ABO07Entities")
        {
            /* Debut ZEG 02/06/2020*/
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 1200;
            System.Data.Common.DbConnection laChaineDeConnexion = ((IObjectContextAdapter)this).ObjectContext.Connection;

            string[] caract = laChaineDeConnexion.ConnectionString.Split(new string[] { "data source" }, StringSplitOptions.RemoveEmptyEntries);
            string[] chaine = caract[1].Split(new string[] { "MultipleActiveResultSetsnew" }, StringSplitOptions.RemoveEmptyEntries);
            string[] connexion = chaine[0].Split(new Char[] { ';' });
            string[] uid = connexion[2].Split(new string[] { "user id=" }, StringSplitOptions.RemoveEmptyEntries);
            string[] pwd = connexion[3].Split(new string[] { "password=" }, StringSplitOptions.RemoveEmptyEntries);

            string userId = string.Empty;
            string password = string.Empty;

            if (!string.IsNullOrEmpty(uid[0]))
                userId = INOVA.GALATEE.SECURITY.Crypteur.DecrypterText(uid[0]);

            if (!string.IsNullOrEmpty(pwd[0]))
                password = INOVA.GALATEE.SECURITY.Crypteur.DecrypterText(pwd[0]);

            string connectionString = caract[0] + "data source" + connexion[0] + ";" + connexion[1] + ";user id=" + userId + ";password=" + password + ";" + connexion[4] + ";" + connexion[5];

            ((IObjectContextAdapter)this).ObjectContext.Connection.ConnectionString = connectionString;

            /** Fin **/
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CENTFAC> CENTFAC { get; set; }
        public DbSet<CPROFAC> CPROFAC { get; set; }
        public DbSet<CREDFAC> CREDFAC { get; set; }
    }
}
