//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiviteCouleur
    {
        public Nullable<int> Couleur_ID { get; set; }
        public System.Guid PK_ID { get; set; }
        public Nullable<int> Activite_ID { get; set; }
    
        public virtual RefActivite RefActivite { get; set; }
        public virtual RefCouleurlot RefCouleurlot { get; set; }
    }
}
