//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFFECTATIONDEMANDEUSER
    {
        public System.Guid PK_ID { get; set; }
        public string CODEDEMANDE { get; set; }
        public string MATRICULEUSER { get; set; }
        public int FK_IDETAPE { get; set; }
        public System.Guid OPERATIONID { get; set; }
        public System.Guid WORKFLOWID { get; set; }
        public int CENTREID { get; set; }
        public Nullable<int> FK_IDETAPEFROM { get; set; }
        public string MATRICULEUSERCREATION { get; set; }
        public Nullable<int> FK_IDUSERAFFECTER { get; set; }
        public Nullable<int> FK_IDDEMANDE { get; set; }
    
        public virtual ADMUTILISATEUR ADMUTILISATEUR { get; set; }
        public virtual DEMANDE DEMANDE { get; set; }
    }
}
