//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANNUL
    {
        public string CENTRE { get; set; }
        public string CLIENT { get; set; }
        public string ORDRE { get; set; }
        public string JET { get; set; }
        public string FACTURE { get; set; }
        public string PIECE { get; set; }
        public string EVT { get; set; }
        public Nullable<short> NBEVT { get; set; }
        public string TOPMAJ { get; set; }
        public string LIENFAC { get; set; }
        public string MOTIF { get; set; }
        public Nullable<short> IMPLICATION { get; set; }
        public string NVNDOC { get; set; }
        public string PERIODE { get; set; }
        public Nullable<int> RECALCUL { get; set; }
        public byte[] ROWID { get; set; }
    }
}
