//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANQUE
    {
        public BANQUE()
        {
            this.AGENCEBANQUE = new HashSet<AGENCEBANQUE>();
            this.DOMBANC = new HashSet<DOMBANC>();
        }
    
        public int PK_ID { get; set; }
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public string USERCREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public Nullable<decimal> FRAISDERETOUR { get; set; }
    
        public virtual ICollection<AGENCEBANQUE> AGENCEBANQUE { get; set; }
        public virtual ICollection<DOMBANC> DOMBANC { get; set; }
    }
}
