//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_REJET_BRT
    {
        public string CENTRE { get; set; }
        public string CLIENT { get; set; }
        public string NUMDEM { get; set; }
        public string PRODUIT { get; set; }
        public Nullable<System.DateTime> DRAC { get; set; }
        public Nullable<System.DateTime> DRES { get; set; }
        public string SERVICE { get; set; }
        public string CATBRT { get; set; }
        public string DIAMBRT { get; set; }
        public Nullable<decimal> LONGBRT { get; set; }
        public string NATBRT { get; set; }
        public Nullable<int> NBPOINT { get; set; }
        public string RESEAU { get; set; }
        public string TRONCON { get; set; }
        public Nullable<System.DateTime> DMAJ { get; set; }
        public string TRANSFORMATEUR { get; set; }
        public Nullable<decimal> PUISSANCEINSTALLEE { get; set; }
        public Nullable<decimal> PERTES { get; set; }
        public Nullable<decimal> COEFPERTES { get; set; }
        public string APPTRANSFO { get; set; }
        public string CODEBRT { get; set; }
        public string CODEPOSTE { get; set; }
        public string MARQUETRANSFO { get; set; }
        public string ANFAB { get; set; }
        public string LONGITUDE { get; set; }
        public string LATITUDE { get; set; }
        public string ADRESSERESEAU { get; set; }
        public string USERCREATION { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public Nullable<int> FK_IDCENTRE { get; set; }
        public Nullable<int> FK_IDPRODUIT { get; set; }
        public Nullable<int> FK_IDTYPEBRANCHEMENT { get; set; }
        public Nullable<int> FK_IDAG { get; set; }
        public Nullable<int> FK_IDDEMANDE { get; set; }
    }
}
