//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIECLIENT_USAGE
    {
        public int PK_ID { get; set; }
        public Nullable<int> FK_IDCATEGORIECLIENT { get; set; }
        public Nullable<int> FK_IDUSAGE { get; set; }
    
        public virtual CATEGORIECLIENT CATEGORIECLIENT { get; set; }
        public virtual USAGE USAGE { get; set; }
    }
}
