//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTAIRE_REJET
    {
        public System.Guid PK_ID { get; set; }
        public System.DateTime DATECOMMENTAIRE { get; set; }
        public string COMMENTAIRE { get; set; }
        public byte[] PIECE_JOINTE { get; set; }
        public string CODEDEMANDE { get; set; }
        public System.Guid FK_IDDEMANDE { get; set; }
        public string UTILISATEUR { get; set; }
        public Nullable<int> FK_IDETAPE { get; set; }
    
        public virtual ETAPE ETAPE { get; set; }
        public virtual DEMANDE_WORFKLOW DEMANDE_WORFKLOW { get; set; }
    }
}
