//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPTA_ECRITURECOMPTABLE
    {
        public string SITE { get; set; }
        public string CENTRE { get; set; }
        public string CAISSE { get; set; }
        public string INITIAL { get; set; }
        public string CODEINTERFACE { get; set; }
        public string NEGATIVE { get; set; }
        public string PROVENACE { get; set; }
        public string DESCRIPSTIONOPERATION { get; set; }
        public string DATEOPERATION { get; set; }
        public string DEVISE { get; set; }
        public string DATEGENERATION { get; set; }
        public string ZERO { get; set; }
        public string ALPHA { get; set; }
        public string SOCIETE { get; set; }
        public string ACTIVITE { get; set; }
        public string COMPTE { get; set; }
        public string CENTREIMPUTATION { get; set; }
        public string FILIERE { get; set; }
        public string SOUSCOMPTE { get; set; }
        public string LOCALISATION { get; set; }
        public string NATUREIMMO { get; set; }
        public string LIBRE { get; set; }
        public Nullable<decimal> DEBIT { get; set; }
        public Nullable<decimal> CREDIT { get; set; }
        public Nullable<decimal> DEBIT1 { get; set; }
        public Nullable<decimal> CREDIT1 { get; set; }
        public string LIBELLEOPERATION { get; set; }
        public string NUMPIECE { get; set; }
        public string NO { get; set; }
        public string DESCRIPTIONLIGNE { get; set; }
        public int PK_ID { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFCATION { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public Nullable<int> FK_IDOPERATION { get; set; }
    }
}
