//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COPER
    {
        public COPER()
        {
            this.AJUFIN = new HashSet<AJUFIN>();
            this.CODECONTROLE = new HashSet<CODECONTROLE>();
            this.COMPTA_OPERATIONCOMPTABLE = new HashSet<COMPTA_OPERATIONCOMPTABLE>();
            this.COUTDEMANDE = new HashSet<COUTDEMANDE>();
            this.ELEMENTACHATTIMBRE = new HashSet<ELEMENTACHATTIMBRE>();
            this.ELEMENTDEVIS = new HashSet<ELEMENTDEVIS>();
            this.FACTUREFRAUDE = new HashSet<FACTUREFRAUDE>();
            this.LCLIENT = new HashSet<LCLIENT>();
            this.LCLIENTFRAUDE = new HashSet<LCLIENTFRAUDE>();
            this.MODEREG = new HashSet<MODEREG>();
            this.NATGEN = new HashSet<NATGEN>();
            this.RUBRIQUEDEMANDE = new HashSet<RUBRIQUEDEMANDE>();
            this.TRANSCAISB = new HashSet<TRANSCAISB>();
            this.TRANSCAISBFRAUDE = new HashSet<TRANSCAISBFRAUDE>();
            this.TRANSCAISSE = new HashSet<TRANSCAISSE>();
            this.TRANSCAISSEFRAUDE = new HashSet<TRANSCAISSEFRAUDE>();
            this.TYPECOUPURE = new HashSet<TYPECOUPURE>();
            this.DETAILLOT = new HashSet<DETAILLOT>();
        }
    
        public string CODE { get; set; }
        public string LIBCOURT { get; set; }
        public string LIBELLE { get; set; }
        public string COMPTGENE { get; set; }
        public string DC { get; set; }
        public string CTRAIT { get; set; }
        public Nullable<System.DateTime> DMAJ { get; set; }
        public string TRANS { get; set; }
        public string COMPTEANNEXE1 { get; set; }
        public string USERCREATION { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int PK_ID { get; set; }
        public Nullable<bool> ISOD { get; set; }
    
        public virtual ICollection<AJUFIN> AJUFIN { get; set; }
        public virtual ICollection<CODECONTROLE> CODECONTROLE { get; set; }
        public virtual ICollection<COMPTA_OPERATIONCOMPTABLE> COMPTA_OPERATIONCOMPTABLE { get; set; }
        public virtual ICollection<COUTDEMANDE> COUTDEMANDE { get; set; }
        public virtual ICollection<ELEMENTACHATTIMBRE> ELEMENTACHATTIMBRE { get; set; }
        public virtual ICollection<ELEMENTDEVIS> ELEMENTDEVIS { get; set; }
        public virtual ICollection<FACTUREFRAUDE> FACTUREFRAUDE { get; set; }
        public virtual ICollection<LCLIENT> LCLIENT { get; set; }
        public virtual ICollection<LCLIENTFRAUDE> LCLIENTFRAUDE { get; set; }
        public virtual ICollection<MODEREG> MODEREG { get; set; }
        public virtual ICollection<NATGEN> NATGEN { get; set; }
        public virtual ICollection<RUBRIQUEDEMANDE> RUBRIQUEDEMANDE { get; set; }
        public virtual ICollection<TRANSCAISB> TRANSCAISB { get; set; }
        public virtual ICollection<TRANSCAISBFRAUDE> TRANSCAISBFRAUDE { get; set; }
        public virtual ICollection<TRANSCAISSE> TRANSCAISSE { get; set; }
        public virtual ICollection<TRANSCAISSEFRAUDE> TRANSCAISSEFRAUDE { get; set; }
        public virtual ICollection<TYPECOUPURE> TYPECOUPURE { get; set; }
        public virtual ICollection<DETAILLOT> DETAILLOT { get; set; }
    }
}
