//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTARCOMPPARPERIODE
    {
        public int PK_ID { get; set; }
        public string RECHERCHETARIF { get; set; }
        public int FK_IDCENTRETARIF { get; set; }
        public int FK_IDPRODUIT { get; set; }
        public int FK_IDABON { get; set; }
        public string LOTRI { get; set; }
        public string PERIODE { get; set; }
        public string CTARCOMP { get; set; }
    
        public virtual ABON ABON { get; set; }
        public virtual CENTRE CENTRE { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
