//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTARCOMP
    {
        public int FK_IDRECHERCHETARIF { get; set; }
        public byte ORDRE { get; set; }
        public int FK_IDCONTENANTCRITERETARIF { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
    
        public virtual CONTENANTCRITERETARIF CONTENANTCRITERETARIF { get; set; }
        public virtual RECHERCHETARIF RECHERCHETARIF { get; set; }
    }
}
