//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCLIENT
    {
        public string CENTRE { get; set; }
        public string REFCLIENT { get; set; }
        public string ORDRE { get; set; }
        public string CODEIDENTIFICATIONNATIONALE { get; set; }
        public string NUMDEM { get; set; }
        public string DENABON { get; set; }
        public string NOMABON { get; set; }
        public string DENMAND { get; set; }
        public string NOMMAND { get; set; }
        public string ADRMAND1 { get; set; }
        public string ADRMAND2 { get; set; }
        public string CPOS { get; set; }
        public string BUREAU { get; set; }
        public Nullable<System.DateTime> DINC { get; set; }
        public string MODEPAIEMENT { get; set; }
        public string NOMTIT { get; set; }
        public string BANQUE { get; set; }
        public string GUICHET { get; set; }
        public string COMPTE { get; set; }
        public string RIB { get; set; }
        public string PROPRIO { get; set; }
        public string CODECONSO { get; set; }
        public string CATEGORIE { get; set; }
        public string CODERELANCE { get; set; }
        public string NOMCOD { get; set; }
        public string MOISNAIS { get; set; }
        public string ANNAIS { get; set; }
        public string NOMPERE { get; set; }
        public string NOMMERE { get; set; }
        public string NATIONNALITE { get; set; }
        public string CNI { get; set; }
        public string TELEPHONE { get; set; }
        public string MATRICULE { get; set; }
        public string REGROUPEMENT { get; set; }
        public string REGEDIT { get; set; }
        public string FACTURE { get; set; }
        public Nullable<System.DateTime> DMAJ { get; set; }
        public Nullable<int> REFERENCEPUPITRE { get; set; }
        public Nullable<int> PAYEUR { get; set; }
        public string SOUSACTIVITE { get; set; }
        public string AGENTFACTURE { get; set; }
        public string AGENTRECOUVR { get; set; }
        public string AGENTASSAINI { get; set; }
        public string REGROUCONTRAT { get; set; }
        public string INSPECTION { get; set; }
        public string REGLEMENT { get; set; }
        public string DECRET { get; set; }
        public string CONVENTION { get; set; }
        public string REFERENCEATM { get; set; }
        public int PK_ID { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int FK_IDMODEPAIEMENT { get; set; }
        public int FK_IDCODECONSO { get; set; }
        public int FK_IDCATEGORIE { get; set; }
        public int FK_IDRELANCE { get; set; }
        public int FK_IDNATIONALITE { get; set; }
        public int FK_IDCENTRE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ISFACTUREEMAIL { get; set; }
        public Nullable<bool> ISFACTURESMS { get; set; }
        public Nullable<int> FK_IDPAYEUR { get; set; }
        public Nullable<int> FK_IDREGROUPEMENT { get; set; }
        public int FK_IDPROPRIETAIRE { get; set; }
        public int FK_IDDEMANDE { get; set; }
        public Nullable<int> FK_IDPIECEIDENTITE { get; set; }
        public string NUMEROPIECEIDENTITE { get; set; }
        public string NUMPROPRIETE { get; set; }
        public Nullable<int> FK_TYPECLIENT { get; set; }
        public string FAX { get; set; }
        public string BOITEPOSTAL { get; set; }
        public Nullable<int> FK_IDUSAGE { get; set; }
        public string TELEPHONEFIXE { get; set; }
        public Nullable<int> FK_IDAG { get; set; }
        public Nullable<bool> ISMODIFIER { get; set; }
    
        public virtual CATEGORIECLIENT CATEGORIECLIENT { get; set; }
        public virtual CENTRE CENTRE1 { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual CODECONSOMMATEUR CODECONSOMMATEUR { get; set; }
        public virtual RELANCE RELANCE { get; set; }
        public virtual MODEPAIEMENT MODEPAIEMENT1 { get; set; }
        public virtual NATIONALITE NATIONALITE { get; set; }
        public virtual PAYEUR PAYEUR1 { get; set; }
        public virtual PIECEIDENTITE PIECEIDENTITE { get; set; }
        public virtual PROPRIETAIRE PROPRIETAIRE { get; set; }
        public virtual REGROUPEMENT REGROUPEMENT1 { get; set; }
        public virtual TYPECLIENT TYPECLIENT { get; set; }
        public virtual USAGE USAGE { get; set; }
        public virtual DEMANDE DEMANDE { get; set; }
    }
}
