//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMANDE
    {
        public DEMANDE()
        {
            this.APPAREILSDEVIS = new HashSet<APPAREILSDEVIS>();
            this.CONTROLETRAVAUX = new HashSet<CONTROLETRAVAUX>();
            this.DABON = new HashSet<DABON>();
            this.DADMINISTRATION_INSTITUT = new HashSet<DADMINISTRATION_INSTITUT>();
            this.DAG = new HashSet<DAG>();
            this.DANNOTATION = new HashSet<DANNOTATION>();
            this.DAUTORISATIONCAISSE = new HashSet<DAUTORISATIONCAISSE>();
            this.DBRT = new HashSet<DBRT>();
            this.DCANALISATION = new HashSet<DCANALISATION>();
            this.DCLIENT = new HashSet<DCLIENT>();
            this.DCOMPTEUR = new HashSet<DCOMPTEUR>();
            this.AffectationScelle = new HashSet<AffectationScelle>();
            this.DEPANNAGE = new HashSet<DEPANNAGE>();
            this.DEVENEMENT = new HashSet<DEVENEMENT>();
            this.DORDRETRAVAIL = new HashSet<DORDRETRAVAIL>();
            this.DPERSONNEPHYSIQUE = new HashSet<DPERSONNEPHYSIQUE>();
            this.DSCELLE = new HashSet<DSCELLE>();
            this.DSOCIETEPRIVE = new HashSet<DSOCIETEPRIVE>();
            this.DTRANSFERT = new HashSet<DTRANSFERT>();
            this.ELEMENTACHATTIMBRE = new HashSet<ELEMENTACHATTIMBRE>();
            this.ELEMENTDEVIS = new HashSet<ELEMENTDEVIS>();
            this.FRAIXPARICIPATIONDEVIS = new HashSet<FRAIXPARICIPATIONDEVIS>();
            this.FRAUDE = new HashSet<FRAUDE>();
            this.DINFOPROPRIETAIRE = new HashSet<DINFOPROPRIETAIRE>();
            this.POSE_SCELLE_DEMANDE = new HashSet<POSE_SCELLE_DEMANDE>();
            this.PROGRAMMATION = new HashSet<PROGRAMMATION>();
            this.RUBRIQUEDEMANDE = new HashSet<RUBRIQUEDEMANDE>();
            this.SUIVIDEMANDE = new HashSet<SUIVIDEMANDE>();
            this.TRAVAUXDEVIS = new HashSet<TRAVAUXDEVIS>();
            this.RCL_Reclamation = new HashSet<RCL_Reclamation>();
            this.AFFECTATIONDEMANDEUSER = new HashSet<AFFECTATIONDEMANDEUSER>();
            this.ACTIONSURDEMANDE = new HashSet<ACTIONSURDEMANDE>();
            this.DOCUMENTSCANNE = new HashSet<DOCUMENTSCANNE>();
        }
    
        public string NUMDEM { get; set; }
        public string CENTRE { get; set; }
        public string NUMPERE { get; set; }
        public string TYPEDEMANDE { get; set; }
        public Nullable<System.DateTime> DPRRDV { get; set; }
        public Nullable<System.DateTime> DPRDEV { get; set; }
        public Nullable<System.DateTime> DPREX { get; set; }
        public Nullable<System.DateTime> DREARDV { get; set; }
        public Nullable<System.DateTime> DREADEV { get; set; }
        public Nullable<System.DateTime> DREAEX { get; set; }
        public string HRDVPR { get; set; }
        public string FDEM { get; set; }
        public string FREP { get; set; }
        public string NOMPERE { get; set; }
        public string NOMMERE { get; set; }
        public string MATRICULE { get; set; }
        public string STATUT { get; set; }
        public Nullable<System.DateTime> DCAISSE { get; set; }
        public string NCAISSE { get; set; }
        public string EXDAG { get; set; }
        public string EXDBRT { get; set; }
        public string PRODUIT { get; set; }
        public string EXCL { get; set; }
        public string CLIENT { get; set; }
        public string EXCOMPT { get; set; }
        public string COMPTEUR { get; set; }
        public string EXEVT { get; set; }
        public string CTAXEG { get; set; }
        public Nullable<System.DateTime> DATED { get; set; }
        public string REFEM { get; set; }
        public string ORDRE { get; set; }
        public string TOPEDIT { get; set; }
        public string FACTURE { get; set; }
        public string OPERATIONDIVERSE { get; set; }
        public Nullable<System.DateTime> DATEFLAG { get; set; }
        public string USERCREATION { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public Nullable<int> ETAPEDEMANDE { get; set; }
        public int PK_ID { get; set; }
        public int FK_IDCENTRE { get; set; }
        public Nullable<int> FK_IDCLIENT { get; set; }
        public Nullable<int> FK_IDADMUTILISATEUR { get; set; }
        public int FK_IDTYPEDEMANDE { get; set; }
        public Nullable<int> FK_IDPRODUIT { get; set; }
        public Nullable<bool> TRANSMIS { get; set; }
        public string STATUTDEMANDE { get; set; }
        public string ANNOTATION { get; set; }
        public Nullable<System.Guid> FICHIERJOINT { get; set; }
        public Nullable<bool> ISSUPPRIME { get; set; }
        public string USERSUPPRESSION { get; set; }
        public Nullable<System.DateTime> DATESUPPRESSION { get; set; }
        public Nullable<bool> ISEXTENSION { get; set; }
        public Nullable<bool> ISPRESTATION { get; set; }
        public Nullable<bool> ISFOURNITURE { get; set; }
        public Nullable<bool> ISPOSE { get; set; }
        public string MOTIF { get; set; }
        public Nullable<int> FK_IDTYPECLIENT { get; set; }
        public Nullable<bool> ISCHANGECOMPTEUR { get; set; }
        public Nullable<bool> ISCONTROLE { get; set; }
        public Nullable<System.DateTime> DATEFIN { get; set; }
        public string TYPECOMPTAGE { get; set; }
        public Nullable<int> FK_IDTYPECOMPTAGE { get; set; }
        public Nullable<int> FK_IDPUISSANCESOUSCRITE { get; set; }
        public Nullable<int> FK_IDREGLAGECOMPTEUR { get; set; }
        public Nullable<bool> ISMUTATION { get; set; }
        public string REGLAGECOMPTEUR { get; set; }
        public Nullable<decimal> PUISSANCESOUSCRITE { get; set; }
        public Nullable<bool> ISGRANDCOMPTE { get; set; }
        public Nullable<bool> ISETALONNAGE { get; set; }
        public Nullable<bool> ISDEMANDEREJETERINIT { get; set; }
        public Nullable<bool> ISMETREAFAIRE { get; set; }
        public Nullable<bool> ISBONNEINITIATIVE { get; set; }
        public Nullable<bool> ISDEVISCOMPLEMENTAIRE { get; set; }
        public Nullable<int> NOMBREDEFOYER { get; set; }
        public Nullable<bool> ISDEFINITIF { get; set; }
        public Nullable<bool> ISPROVISOIR { get; set; }
        public Nullable<int> FK_IDDEMANDE { get; set; }
        public Nullable<bool> ISCOMMUNE { get; set; }
        public Nullable<bool> ISEDM { get; set; }
        public Nullable<bool> ISDEVISHT { get; set; }
        public Nullable<bool> ISPASSERCAISSE { get; set; }
        public Nullable<decimal> ANCIENNEPUISSANCE { get; set; }
        public Nullable<bool> ISPASDEFACTURE { get; set; }
        public string PRESTATAIRE { get; set; }
    
        public virtual ADMUTILISATEUR ADMUTILISATEUR { get; set; }
        public virtual ICollection<APPAREILSDEVIS> APPAREILSDEVIS { get; set; }
        public virtual CENTRE CENTRE1 { get; set; }
        public virtual CLIENT CLIENT1 { get; set; }
        public virtual ICollection<CONTROLETRAVAUX> CONTROLETRAVAUX { get; set; }
        public virtual ICollection<DABON> DABON { get; set; }
        public virtual ICollection<DADMINISTRATION_INSTITUT> DADMINISTRATION_INSTITUT { get; set; }
        public virtual ICollection<DAG> DAG { get; set; }
        public virtual ICollection<DANNOTATION> DANNOTATION { get; set; }
        public virtual ICollection<DAUTORISATIONCAISSE> DAUTORISATIONCAISSE { get; set; }
        public virtual ICollection<DBRT> DBRT { get; set; }
        public virtual ICollection<DCANALISATION> DCANALISATION { get; set; }
        public virtual ICollection<DCLIENT> DCLIENT { get; set; }
        public virtual ICollection<DCOMPTEUR> DCOMPTEUR { get; set; }
        public virtual ICollection<AffectationScelle> AffectationScelle { get; set; }
        public virtual PRODUIT PRODUIT1 { get; set; }
        public virtual PUISSANCESOUSCRITE PUISSANCESOUSCRITE1 { get; set; }
        public virtual REGLAGECOMPTEUR REGLAGECOMPTEUR1 { get; set; }
        public virtual TYPECOMPTAGE TYPECOMPTAGE1 { get; set; }
        public virtual TYPEDEMANDE TYPEDEMANDE1 { get; set; }
        public virtual ICollection<DEPANNAGE> DEPANNAGE { get; set; }
        public virtual ICollection<DEVENEMENT> DEVENEMENT { get; set; }
        public virtual ICollection<DORDRETRAVAIL> DORDRETRAVAIL { get; set; }
        public virtual ICollection<DPERSONNEPHYSIQUE> DPERSONNEPHYSIQUE { get; set; }
        public virtual ICollection<DSCELLE> DSCELLE { get; set; }
        public virtual ICollection<DSOCIETEPRIVE> DSOCIETEPRIVE { get; set; }
        public virtual ICollection<DTRANSFERT> DTRANSFERT { get; set; }
        public virtual ICollection<ELEMENTACHATTIMBRE> ELEMENTACHATTIMBRE { get; set; }
        public virtual ICollection<ELEMENTDEVIS> ELEMENTDEVIS { get; set; }
        public virtual ICollection<FRAIXPARICIPATIONDEVIS> FRAIXPARICIPATIONDEVIS { get; set; }
        public virtual ICollection<FRAUDE> FRAUDE { get; set; }
        public virtual ICollection<DINFOPROPRIETAIRE> DINFOPROPRIETAIRE { get; set; }
        public virtual ICollection<POSE_SCELLE_DEMANDE> POSE_SCELLE_DEMANDE { get; set; }
        public virtual ICollection<PROGRAMMATION> PROGRAMMATION { get; set; }
        public virtual ICollection<RUBRIQUEDEMANDE> RUBRIQUEDEMANDE { get; set; }
        public virtual ICollection<SUIVIDEMANDE> SUIVIDEMANDE { get; set; }
        public virtual ICollection<TRAVAUXDEVIS> TRAVAUXDEVIS { get; set; }
        public virtual ICollection<RCL_Reclamation> RCL_Reclamation { get; set; }
        public virtual ICollection<AFFECTATIONDEMANDEUSER> AFFECTATIONDEMANDEUSER { get; set; }
        public virtual ICollection<ACTIONSURDEMANDE> ACTIONSURDEMANDE { get; set; }
        public virtual ICollection<DOCUMENTSCANNE> DOCUMENTSCANNE { get; set; }
    }
}
