//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPANNAGE
    {
        public string ETAGE { get; set; }
        public string PORTE { get; set; }
        public string TELEPHONE { get; set; }
        public string DESCRIPTIONPANNE { get; set; }
        public int PK_ID { get; set; }
        public Nullable<int> FK_IDQUARTIER { get; set; }
        public Nullable<int> FK_IDCOMMUNE { get; set; }
        public Nullable<int> FK_IDRUE { get; set; }
        public Nullable<int> FK_IDSECTEUR { get; set; }
        public int FK_IDCENTRE { get; set; }
        public Nullable<int> FK_IDDEMANDE { get; set; }
        public string LIEUINTERVANTION { get; set; }
        public Nullable<int> FK_IDMODERECEUIL { get; set; }
        public Nullable<int> FK_IDTYPEDEPANNE { get; set; }
        public Nullable<bool> ISPERSONNEEXTERIEUR { get; set; }
        public Nullable<int> FK_IDDETAILPANNE { get; set; }
        public Nullable<bool> ISEDM { get; set; }
        public Nullable<bool> ISCOMMUNE { get; set; }
        public Nullable<System.TimeSpan> HEUREDEBUT { get; set; }
        public Nullable<System.TimeSpan> HEUREFIN { get; set; }
        public Nullable<bool> ISRESEAU { get; set; }
        public Nullable<bool> ISBRANCHEMENT { get; set; }
        public Nullable<bool> ISPROVISOIR { get; set; }
        public Nullable<bool> ISDEFINITIF { get; set; }
    
        public virtual CENTRE CENTRE { get; set; }
        public virtual COMMUNE COMMUNE { get; set; }
        public virtual GRC_PANNE GRC_PANNE { get; set; }
        public virtual GRC_MODE_COMMUNICATION GRC_MODE_COMMUNICATION { get; set; }
        public virtual GRC_TYPE_RECLAMATION GRC_TYPE_RECLAMATION { get; set; }
        public virtual QUARTIER QUARTIER { get; set; }
        public virtual RUES RUES { get; set; }
        public virtual SECTEUR SECTEUR { get; set; }
        public virtual DEMANDE DEMANDE { get; set; }
    }
}
