//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILparREGULARISATION
    {
        public int PK_ID { get; set; }
        public int NombrePrestation { get; set; }
        public decimal PrixUnitaire { get; set; }
        public int FK_IDCONSOMMATION { get; set; }
        public int FK_IDREGULARISATION { get; set; }
        public int FK_IDPRODUIT { get; set; }
    
        public virtual PRODUIT PRODUIT { get; set; }
        public virtual CONSOMMATION CONSOMMATION { get; set; }
        public virtual REGULARISATION REGULARISATION { get; set; }
    }
}
