//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DINFOPROPRIETAIRE
    {
        public int PK_ID { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public Nullable<System.DateTime> DATENAISSANCE { get; set; }
        public string NUMEROPIECEIDENTITE { get; set; }
        public Nullable<System.DateTime> DATEFINVALIDITE { get; set; }
        public Nullable<int> FK_IDDEMANDE { get; set; }
        public Nullable<int> FK_IDPIECEIDENTITE { get; set; }
        public Nullable<int> FK_IDNATIONNALITE { get; set; }
        public string FAX { get; set; }
        public string BOITEPOSTALE { get; set; }
        public string EMAIL { get; set; }
        public string TELEPHONEMOBILE { get; set; }
        public string TELEPHONEFIXE { get; set; }
    
        public virtual NATIONALITE NATIONALITE { get; set; }
        public virtual PIECEIDENTITE PIECEIDENTITE { get; set; }
        public virtual DEMANDE DEMANDE { get; set; }
    }
}
