//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCUMENTSCANNETemp
    {
        public System.Guid PK_ID { get; set; }
        public string NOMDOCUMENT { get; set; }
        public byte[] CONTENU { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public Nullable<int> FK_IDDEMANDE { get; set; }
        public Nullable<int> FK_IDTYPEDOCUMENT { get; set; }
        public string CHEMINCOPY { get; set; }
        public string NOMDUFICHIER { get; set; }
        public Nullable<bool> ismigre { get; set; }
    }
}
