//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSOCIETEPRIVE
    {
        public int PK_ID { get; set; }
        public string NUMEROREGISTRECOMMERCE { get; set; }
        public Nullable<int> FK_IDSTATUTJURIQUE { get; set; }
        public Nullable<decimal> CAPITAL { get; set; }
        public string IDENTIFICATIONFISCALE { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public string SIEGE { get; set; }
        public Nullable<int> FK_IDDEMANDE { get; set; }
        public string NOMMANDATAIRE { get; set; }
        public string PRENOMMANDATAIRE { get; set; }
        public string RANGMANDATAIRE { get; set; }
        public string NOMSIGNATAIRE { get; set; }
        public string PRENOMSIGNATAIRE { get; set; }
        public string RANGSIGNATAIRE { get; set; }
        public string NOMABON { get; set; }
    
        public virtual STATUTJURIQUE STATUTJURIQUE { get; set; }
        public virtual DEMANDE DEMANDE { get; set; }
    }
}
