//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENTDEVIS
    {
        public string NUMDEM { get; set; }
        public int ORDRE { get; set; }
        public string NUMFOURNITURE { get; set; }
        public Nullable<bool> ISEXTENSION { get; set; }
        public Nullable<int> QUANTITE { get; set; }
        public Nullable<int> QUANTITEREMISENSTOCK { get; set; }
        public Nullable<int> QUANTITECONSOMMEE { get; set; }
        public Nullable<int> QUANTITEPREVUE { get; set; }
        public Nullable<int> QUANTITELIVREE { get; set; }
        public Nullable<decimal> TAXE { get; set; }
        public Nullable<decimal> MONTANT { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int PK_ID { get; set; }
        public int FK_IDDEMANDE { get; set; }
        public int FK_IDFOURNITURE { get; set; }
        public bool ISFOURNITURE { get; set; }
        public bool ISPOSE { get; set; }
        public bool ISPRESTATION { get; set; }
        public Nullable<int> FK_IDCOUTCOPER { get; set; }
        public Nullable<int> FK_IDCOPER { get; set; }
        public Nullable<int> FK_IDTAXE { get; set; }
        public Nullable<int> FK_IDTYPEDEMANDE { get; set; }
        public Nullable<int> FK_IDMATERIELDEVIS { get; set; }
        public Nullable<decimal> MONTANTHT { get; set; }
        public Nullable<decimal> MONTANTTAXE { get; set; }
        public Nullable<decimal> MONTANTTTC { get; set; }
        public string NOM { get; set; }
        public Nullable<decimal> COUTUNITAIRE_FOURNITURE { get; set; }
        public Nullable<decimal> COUTUNITAIRE_POSE { get; set; }
        public string RUBRIQUE { get; set; }
        public Nullable<int> FK_IDRUBRIQUEDEVIS { get; set; }
        public Nullable<bool> ISPM { get; set; }
    
        public virtual COPER COPER { get; set; }
        public virtual COUTDEMANDE COUTDEMANDE { get; set; }
        public virtual MATERIELDEVIS MATERIELDEVIS { get; set; }
        public virtual PUISSANCESOUSCRITE PUISSANCESOUSCRITE { get; set; }
        public virtual TAXE TAXE1 { get; set; }
        public virtual DEMANDE DEMANDE { get; set; }
    }
}
