//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELEMENTACHATTIMBRE
    {
        public string NUMDEM { get; set; }
        public Nullable<int> QUANTITE { get; set; }
        public Nullable<decimal> TAXE { get; set; }
        public Nullable<decimal> MONTANT { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int PK_ID { get; set; }
        public int FK_IDDEMANDE { get; set; }
        public int FK_IDTIMBRE { get; set; }
        public Nullable<int> FK_IDCOPER { get; set; }
        public Nullable<int> FK_IDTAXE { get; set; }
    
        public virtual COPER COPER { get; set; }
        public virtual TYPETIMBRE TYPETIMBRE { get; set; }
        public virtual TAXE TAXE1 { get; set; }
        public virtual DEMANDE DEMANDE { get; set; }
    }
}
