//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETAPE
    {
        public ETAPE()
        {
            this.SUIVIDEMANDE = new HashSet<SUIVIDEMANDE>();
            this.RAFFECTATIONETAPEWORKFLOW = new HashSet<RAFFECTATIONETAPEWORKFLOW>();
            this.COMMENTAIRE_REJET = new HashSet<COMMENTAIRE_REJET>();
            this.DANNOTATION = new HashSet<DANNOTATION>();
            this.JOURNAL_DEMANDE_WORKFLOW = new HashSet<JOURNAL_DEMANDE_WORKFLOW>();
        }
    
        public int PK_ID { get; set; }
        public string CODE { get; set; }
        public string NOM { get; set; }
        public string CONTROLEETAPE { get; set; }
        public string DESCRIPTIONETAPE { get; set; }
        public Nullable<int> FK_IDMENU { get; set; }
        public Nullable<int> FK_IDFORMULAIRE { get; set; }
        public Nullable<bool> ISMODIFICATION { get; set; }
        public Nullable<System.Guid> FK_IDOPERATION { get; set; }
        public Nullable<bool> IS_TRAITEMENT_LOT { get; set; }
    
        public virtual ICollection<SUIVIDEMANDE> SUIVIDEMANDE { get; set; }
        public virtual ICollection<RAFFECTATIONETAPEWORKFLOW> RAFFECTATIONETAPEWORKFLOW { get; set; }
        public virtual ICollection<COMMENTAIRE_REJET> COMMENTAIRE_REJET { get; set; }
        public virtual ICollection<DANNOTATION> DANNOTATION { get; set; }
        public virtual ICollection<JOURNAL_DEMANDE_WORKFLOW> JOURNAL_DEMANDE_WORKFLOW { get; set; }
    }
}
