//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETAPEDEMANDE
    {
        public string CONTROLEETAPE { get; set; }
        public string LIBELLEETAPE { get; set; }
        public string TYPEDEMANDE { get; set; }
        public int ORDRE { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public int PK_ID { get; set; }
        public int FK_IDTYPEDEMANDE { get; set; }
    
        public virtual TYPEDEMANDE TYPEDEMANDE1 { get; set; }
    }
}
