//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRC_PANNE
    {
        public GRC_PANNE()
        {
            this.DEPANNAGE = new HashSet<DEPANNAGE>();
            this.TRAVAUXDEVIS = new HashSet<TRAVAUXDEVIS>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public int ID_TYPE_RECLAMATION { get; set; }
        public bool EST_SUPPRIME { get; set; }
        public string CREER_PAR { get; set; }
        public Nullable<System.DateTime> DATE_CREATION { get; set; }
        public string DERNIER_UTILISATEUR { get; set; }
        public Nullable<System.DateTime> DATE_MODIFICATION { get; set; }
    
        public virtual ICollection<DEPANNAGE> DEPANNAGE { get; set; }
        public virtual ICollection<TRAVAUXDEVIS> TRAVAUXDEVIS { get; set; }
        public virtual GRC_TYPE_RECLAMATION GRC_TYPE_RECLAMATION { get; set; }
    }
}
