//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUPE_VALIDATION
    {
        public GROUPE_VALIDATION()
        {
            this.COMMUNEGROUPEDEPANNAGE = new HashSet<COMMUNEGROUPEDEPANNAGE>();
            this.RAFFECTATIONETAPEWORKFLOW = new HashSet<RAFFECTATIONETAPEWORKFLOW>();
            this.RHABILITATIONGROUPEVALIDATION = new HashSet<RHABILITATIONGROUPEVALIDATION>();
        }
    
        public System.Guid PK_ID { get; set; }
        public string GROUPENAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string EMAILDIFFUSION { get; set; }
        public bool UNESEULEVALIDATION { get; set; }
        public Nullable<bool> ISDEPANNAGE { get; set; }
        public Nullable<int> VALEURSPECIFIQUE { get; set; }
    
        public virtual ICollection<COMMUNEGROUPEDEPANNAGE> COMMUNEGROUPEDEPANNAGE { get; set; }
        public virtual ICollection<RAFFECTATIONETAPEWORKFLOW> RAFFECTATIONETAPEWORKFLOW { get; set; }
        public virtual ICollection<RHABILITATIONGROUPEVALIDATION> RHABILITATIONGROUPEVALIDATION { get; set; }
    }
}
