//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOURNAL_DEMANDE_WORKFLOW
    {
        public System.Guid PK_ID { get; set; }
        public System.DateTime DATEACTION { get; set; }
        public string MATRICULEUSERACTION { get; set; }
        public string LIBELLEACTION { get; set; }
        public string OBSERVATIONS { get; set; }
        public System.Guid FK_IDDEMANDE { get; set; }
        public string CODE_DEMANDE { get; set; }
        public Nullable<int> FK_IDETAPE { get; set; }
    
        public virtual ETAPE ETAPE { get; set; }
    }
}
