//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTRI
    {
        public string NUMLOTRI { get; set; }
        public string JET { get; set; }
        public string PERIODE { get; set; }
        public string CENTRE { get; set; }
        public string PRODUIT { get; set; }
        public string CATEGORIECLIENT { get; set; }
        public string PERIODICITE { get; set; }
        public Nullable<int> EXIG { get; set; }
        public Nullable<System.DateTime> DFAC { get; set; }
        public string ETATFAC1 { get; set; }
        public string ETATFAC2 { get; set; }
        public string ETATFAC3 { get; set; }
        public string ETATFAC4 { get; set; }
        public string ETATFAC5 { get; set; }
        public string ETATFAC6 { get; set; }
        public string ETATFAC7 { get; set; }
        public string ETATFAC8 { get; set; }
        public string ETATFAC9 { get; set; }
        public string ETATFAC10 { get; set; }
        public string TOURNEE { get; set; }
        public string RELEVEUR { get; set; }
        public string BASE { get; set; }
        public int PK_ID { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public Nullable<int> FK_IDPRODUIT { get; set; }
        public Nullable<int> FK_IDCATEGORIECLIENT { get; set; }
        public Nullable<int> FK_IDRELEVEUR { get; set; }
        public string UserCalcul { get; set; }
        public Nullable<int> FK_IDTOURNEE { get; set; }
        public int FK_IDCENTRE { get; set; }
    
        public virtual CATEGORIECLIENT CATEGORIECLIENT1 { get; set; }
        public virtual CENTRE CENTRE1 { get; set; }
        public virtual PRODUIT PRODUIT1 { get; set; }
        public virtual TOURNEE TOURNEE1 { get; set; }
        public virtual RELEVEUR RELEVEUR1 { get; set; }
    }
}
