//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANDATEMENTGC
    {
        public MANDATEMENTGC()
        {
            this.DETAILMANDATEMENTGC = new HashSet<DETAILMANDATEMENTGC>();
            this.PAIEMENTCAMPAGNEGC = new HashSet<PAIEMENTCAMPAGNEGC>();
        }
    
        public Nullable<decimal> MONTANT { get; set; }
        public int PK_ID { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public string NUMEROMANDATEMENT { get; set; }
        public Nullable<int> FK_IDCAMPAGNA { get; set; }
    
        public virtual CAMPAGNEGC CAMPAGNEGC { get; set; }
        public virtual ICollection<DETAILMANDATEMENTGC> DETAILMANDATEMENTGC { get; set; }
        public virtual ICollection<PAIEMENTCAMPAGNEGC> PAIEMENTCAMPAGNEGC { get; set; }
    }
}
