//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARQUECOMPTEUR
    {
        public MARQUECOMPTEUR()
        {
            this.COMPTEUR = new HashSet<COMPTEUR>();
            this.DCOMPTEUR = new HashSet<DCOMPTEUR>();
            this.MAGASINVIRTUEL = new HashSet<MAGASINVIRTUEL>();
            this.MARQUE_MODELE = new HashSet<MARQUE_MODELE>();
            this.COMPTEURFRAUDE = new HashSet<COMPTEURFRAUDE>();
            this.TbCompteurBTA = new HashSet<TbCompteurBTA>();
        }
    
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int PK_ID { get; set; }
        public Nullable<int> COEFFICIENTDEMULTIPLICATION { get; set; }
    
        public virtual ICollection<COMPTEUR> COMPTEUR { get; set; }
        public virtual ICollection<DCOMPTEUR> DCOMPTEUR { get; set; }
        public virtual ICollection<MAGASINVIRTUEL> MAGASINVIRTUEL { get; set; }
        public virtual ICollection<MARQUE_MODELE> MARQUE_MODELE { get; set; }
        public virtual ICollection<COMPTEURFRAUDE> COMPTEURFRAUDE { get; set; }
        public virtual ICollection<TbCompteurBTA> TbCompteurBTA { get; set; }
    }
}
