//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public string SITE { get; set; }
        public string TEXTE { get; set; }
        public Nullable<System.DateTime> DEBUT_VALIDITE { get; set; }
        public Nullable<System.DateTime> FIN_VALIDITE { get; set; }
        public int PK_ID { get; set; }
    }
}
