//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODELE
    {
        public MODELE()
        {
            this.MARQUE_MODELE = new HashSet<MARQUE_MODELE>();
        }
    
        public int MODELE_ID { get; set; }
        public string Libelle_Modele { get; set; }
    
        public virtual ICollection<MARQUE_MODELE> MARQUE_MODELE { get; set; }
    }
}
