//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANE_SCELLABLE
    {
        public ORGANE_SCELLABLE()
        {
            this.ACTIVITEE_ORGANE = new HashSet<ACTIVITEE_ORGANE>();
            this.POSE_SCELLE_DEMANDE = new HashSet<POSE_SCELLE_DEMANDE>();
        }
    
        public int PK_ID { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<int> FK_IDACTIVITE_TERRAIN { get; set; }
    
        public virtual ICollection<ACTIVITEE_ORGANE> ACTIVITEE_ORGANE { get; set; }
        public virtual ICollection<POSE_SCELLE_DEMANDE> POSE_SCELLE_DEMANDE { get; set; }
    }
}
