//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGISOL
    {
        public string LOTRI { get; set; }
        public string CENTRE { get; set; }
        public string TOURNEE { get; set; }
        public string ORDTOUR { get; set; }
        public string CLIENT { get; set; }
        public string PRODUIT { get; set; }
        public int POINT { get; set; }
        public string CAS { get; set; }
        public string STATUT { get; set; }
        public string TOPEDIT { get; set; }
        public string CATEGORIECLIENT { get; set; }
        public string FREQUENCE { get; set; }
        public string TFAC { get; set; }
        public Nullable<System.DateTime> DDEB { get; set; }
        public Nullable<System.DateTime> DFIN { get; set; }
        public Nullable<int> QTEFAC { get; set; }
        public Nullable<int> AIED { get; set; }
        public Nullable<int> NIED { get; set; }
        public string PERFAC { get; set; }
        public string FACTURE { get; set; }
        public int PK_ID { get; set; }
        public int FK_IDEVENEMENT { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int FK_IDPRODUIT { get; set; }
        public int FK_IDCENTRE { get; set; }
        public int FK_IDCATEGORIECLIENT { get; set; }
        public int FK_IDABON { get; set; }
        public int FK_IDTOURNEE { get; set; }
        public bool ISCONSOSEUL { get; set; }
    
        public virtual CATEGORIECLIENT CATEGORIECLIENT1 { get; set; }
        public virtual CENTRE CENTRE1 { get; set; }
        public virtual EVENEMENT EVENEMENT { get; set; }
        public virtual PRODUIT PRODUIT1 { get; set; }
        public virtual TOURNEE TOURNEE1 { get; set; }
    }
}
