//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIECEIDENTITE
    {
        public PIECEIDENTITE()
        {
            this.CLIENT = new HashSet<CLIENT>();
            this.DCLIENT = new HashSet<DCLIENT>();
            this.DINFOPROPRIETAIRE = new HashSet<DINFOPROPRIETAIRE>();
            this.DPERSONNEPHYSIQUE = new HashSet<DPERSONNEPHYSIQUE>();
            this.INFOPROPRIETAIRE = new HashSet<INFOPROPRIETAIRE>();
            this.PERSONNEPHYSIQUE = new HashSet<PERSONNEPHYSIQUE>();
        }
    
        public int PK_ID { get; set; }
        public string LIBELLE { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
    
        public virtual ICollection<CLIENT> CLIENT { get; set; }
        public virtual ICollection<DCLIENT> DCLIENT { get; set; }
        public virtual ICollection<DINFOPROPRIETAIRE> DINFOPROPRIETAIRE { get; set; }
        public virtual ICollection<DPERSONNEPHYSIQUE> DPERSONNEPHYSIQUE { get; set; }
        public virtual ICollection<INFOPROPRIETAIRE> INFOPROPRIETAIRE { get; set; }
        public virtual ICollection<PERSONNEPHYSIQUE> PERSONNEPHYSIQUE { get; set; }
    }
}
