//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSE_SCELLE_DEMANDE
    {
        public int PK_ID { get; set; }
        public string NUM_SCELLE { get; set; }
        public Nullable<int> FK_IDORGANE_SCELLABLE { get; set; }
        public Nullable<int> FK_IDDEMANDE { get; set; }
        public Nullable<int> FK_IDBRT { get; set; }
        public Nullable<int> NOMBRE { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public string USERCREATION { get; set; }
        public byte[] CERTIFICAT { get; set; }
    
        public virtual BRT BRT { get; set; }
        public virtual ORGANE_SCELLABLE ORGANE_SCELLABLE { get; set; }
        public virtual DEMANDE DEMANDE { get; set; }
    }
}
