//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSTECLIENT
    {
        public POSTECLIENT()
        {
            this.TRANSCAISB = new HashSet<TRANSCAISB>();
            this.TRANSCAISBFRAUDE = new HashSet<TRANSCAISBFRAUDE>();
            this.TRANSCAISSE = new HashSet<TRANSCAISSE>();
            this.TRANSCAISSEFRAUDE = new HashSet<TRANSCAISSEFRAUDE>();
        }
    
        public int PK_ID { get; set; }
        public string CODECENTRE { get; set; }
        public string NOMPOSTE { get; set; }
        public int FK_IDCENTRE { get; set; }
        public string IPPOSTE { get; set; }
        public string CHEMINEDITION { get; set; }
        public Nullable<int> FK_IDCAISSE { get; set; }
        public string NUMCAISSE { get; set; }
    
        public virtual CAISSE CAISSE { get; set; }
        public virtual CENTRE CENTRE { get; set; }
        public virtual ICollection<TRANSCAISB> TRANSCAISB { get; set; }
        public virtual ICollection<TRANSCAISBFRAUDE> TRANSCAISBFRAUDE { get; set; }
        public virtual ICollection<TRANSCAISSE> TRANSCAISSE { get; set; }
        public virtual ICollection<TRANSCAISSEFRAUDE> TRANSCAISSEFRAUDE { get; set; }
    }
}
