//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUISSANCESOUSCRITE
    {
        public PUISSANCESOUSCRITE()
        {
            this.COUTDEMANDE = new HashSet<COUTDEMANDE>();
            this.ELEMENTDEVIS = new HashSet<ELEMENTDEVIS>();
            this.PUISSANCEPARREGLAGECOMPTEUR = new HashSet<PUISSANCEPARREGLAGECOMPTEUR>();
            this.DEMANDE = new HashSet<DEMANDE>();
        }
    
        public int PK_ID { get; set; }
        public string PRODUIT { get; set; }
        public string CODE { get; set; }
        public decimal VALEUR { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public string USERCREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int FK_IDPRODUIT { get; set; }
    
        public virtual ICollection<COUTDEMANDE> COUTDEMANDE { get; set; }
        public virtual ICollection<ELEMENTDEVIS> ELEMENTDEVIS { get; set; }
        public virtual PRODUIT PRODUIT1 { get; set; }
        public virtual ICollection<PUISSANCEPARREGLAGECOMPTEUR> PUISSANCEPARREGLAGECOMPTEUR { get; set; }
        public virtual ICollection<DEMANDE> DEMANDE { get; set; }
    }
}
