//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REDEVANCE
    {
        public REDEVANCE()
        {
            this.LIENREDEVANCE = new HashSet<LIENREDEVANCE>();
            this.LIENREDEVANCE1 = new HashSet<LIENREDEVANCE>();
            this.TRANCHEREDEVANCE = new HashSet<TRANCHEREDEVANCE>();
            this.VARIABLETARIF = new HashSet<VARIABLETARIF>();
        }
    
        public string PRODUIT { get; set; }
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int FK_IDPRODUIT { get; set; }
        public int FK_IDTYPELIENREDEVANCE { get; set; }
        public int FK_IDTYPEREDEVANCE { get; set; }
        public int PK_ID { get; set; }
    
        public virtual ICollection<LIENREDEVANCE> LIENREDEVANCE { get; set; }
        public virtual ICollection<LIENREDEVANCE> LIENREDEVANCE1 { get; set; }
        public virtual PRODUIT PRODUIT1 { get; set; }
        public virtual TYPELIENREDEVANCE TYPELIENREDEVANCE { get; set; }
        public virtual TYPEREDEVANCE TYPEREDEVANCE { get; set; }
        public virtual ICollection<TRANCHEREDEVANCE> TRANCHEREDEVANCE { get; set; }
        public virtual ICollection<VARIABLETARIF> VARIABLETARIF { get; set; }
    }
}
