//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefFournisseurs
    {
        public RefFournisseurs()
        {
            this.tbLotMagasinGeneral = new HashSet<tbLotMagasinGeneral>();
        }
    
        public int Fournisseur_ID { get; set; }
        public string Fournisseur_Libelle { get; set; }
    
        public virtual ICollection<tbLotMagasinGeneral> tbLotMagasinGeneral { get; set; }
    }
}
