//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGLAGECOMPTEUR
    {
        public REGLAGECOMPTEUR()
        {
            this.CANALISATION = new HashSet<CANALISATION>();
            this.COUTDEMANDE = new HashSet<COUTDEMANDE>();
            this.DCANALISATION = new HashSet<DCANALISATION>();
            this.PUISSANCEPARREGLAGECOMPTEUR = new HashSet<PUISSANCEPARREGLAGECOMPTEUR>();
            this.COMPTEURFRAUDE = new HashSet<COMPTEURFRAUDE>();
            this.TRANCHEFRAUDE = new HashSet<TRANCHEFRAUDE>();
            this.TYPETARIFPARREGLAGECOMPTEUR = new HashSet<TYPETARIFPARREGLAGECOMPTEUR>();
            this.DEMANDE = new HashSet<DEMANDE>();
        }
    
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<int> REGLAGEMINI { get; set; }
        public Nullable<int> REGLAGEMAXI { get; set; }
        public Nullable<int> REGLAGE { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int PK_ID { get; set; }
        public int FK_IDPRODUIT { get; set; }
        public Nullable<int> FK_IDPHASE { get; set; }
        public Nullable<int> FK_IDCALIBRECOMPTEUR { get; set; }
    
        public virtual CALIBRECOMPTEUR CALIBRECOMPTEUR { get; set; }
        public virtual ICollection<CANALISATION> CANALISATION { get; set; }
        public virtual ICollection<COUTDEMANDE> COUTDEMANDE { get; set; }
        public virtual ICollection<DCANALISATION> DCANALISATION { get; set; }
        public virtual PHASECOMPTEUR PHASECOMPTEUR { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
        public virtual ICollection<PUISSANCEPARREGLAGECOMPTEUR> PUISSANCEPARREGLAGECOMPTEUR { get; set; }
        public virtual ICollection<COMPTEURFRAUDE> COMPTEURFRAUDE { get; set; }
        public virtual ICollection<TRANCHEFRAUDE> TRANCHEFRAUDE { get; set; }
        public virtual ICollection<TYPETARIFPARREGLAGECOMPTEUR> TYPETARIFPARREGLAGECOMPTEUR { get; set; }
        public virtual ICollection<DEMANDE> DEMANDE { get; set; }
    }
}
