//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELEVEUR
    {
        public RELEVEUR()
        {
            this.LOTRI = new HashSet<LOTRI>();
            this.TOURNEERELEVEUR = new HashSet<TOURNEERELEVEUR>();
        }
    
        public string CENTRE { get; set; }
        public string CODE { get; set; }
        public string MATRICULE { get; set; }
        public Nullable<int> FERMEQUOT { get; set; }
        public Nullable<int> FERMEREAL { get; set; }
        public string PORTABLE { get; set; }
        public string USERCREATION { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public Nullable<bool> SUPPRIMER { get; set; }
        public int PK_ID { get; set; }
        public int FK_IDCENTRE { get; set; }
        public Nullable<int> FK_IDUSER { get; set; }
    
        public virtual ADMUTILISATEUR ADMUTILISATEUR { get; set; }
        public virtual CENTRE CENTRE1 { get; set; }
        public virtual ICollection<LOTRI> LOTRI { get; set; }
        public virtual ICollection<TOURNEERELEVEUR> TOURNEERELEVEUR { get; set; }
    }
}
