//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENVOI_REJET
    {
        public System.Guid PK_ID { get; set; }
        public int FK_IDETAPE { get; set; }
        public System.Guid FK_IDRAFFECTATION { get; set; }
        public int FK_IDETAPEACTUELLE { get; set; }
    }
}
