//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVERSEMENTCAISSE
    {
        public int PK_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<decimal> MONTANT { get; set; }
        public Nullable<decimal> RESTE { get; set; }
        public int FK_IDHABILITATIONCAISSE { get; set; }
    
        public virtual HABILITATIONCAISSE HABILITATIONCAISSE { get; set; }
    }
}
