//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TARIFFACTURATION
    {
        public TARIFFACTURATION()
        {
            this.DETAILTARIFFACTURATION = new HashSet<DETAILTARIFFACTURATION>();
        }
    
        public string PRODUIT { get; set; }
        public string REDEVANCE { get; set; }
        public string REGION { get; set; }
        public string SREGION { get; set; }
        public string CENTRE { get; set; }
        public string COMMUNE { get; set; }
        public string RECHERCHETARIF { get; set; }
        public string CTARCOMP { get; set; }
        public System.DateTime DEBUTAPPLICATION { get; set; }
        public Nullable<System.DateTime> FINAPPLICATION { get; set; }
        public string PERDEB { get; set; }
        public string PERFIN { get; set; }
        public string TAXE { get; set; }
        public string UNITE { get; set; }
        public Nullable<decimal> MONTANTANNUEL { get; set; }
        public Nullable<int> MINIVOL { get; set; }
        public Nullable<decimal> MINIVAL { get; set; }
        public Nullable<int> FORFVOL { get; set; }
        public Nullable<decimal> FORFVAL { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERCREATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int FK_IDPRODUIT { get; set; }
        public int FK_IDCENTRE { get; set; }
        public int FK_IDVARIABLETARIF { get; set; }
        public int FK_IDTAXE { get; set; }
        public int FK_IDUNITECOMPTAGE { get; set; }
        public int PK_ID { get; set; }
    
        public virtual CENTRE CENTRE1 { get; set; }
        public virtual ICollection<DETAILTARIFFACTURATION> DETAILTARIFFACTURATION { get; set; }
        public virtual PRODUIT PRODUIT1 { get; set; }
        public virtual TAXE TAXE1 { get; set; }
        public virtual UNITECOMPTAGE UNITECOMPTAGE { get; set; }
        public virtual VARIABLETARIF VARIABLETARIF { get; set; }
    }
}
