//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbCompteurBTA
    {
        public TbCompteurBTA()
        {
            this.MAGASINVIRTUEL = new HashSet<MAGASINVIRTUEL>();
        }
    
        public string Numero_Compteur { get; set; }
        public Nullable<int> Type_Compteur_ID { get; set; }
        public string StatutCompteur { get; set; }
        public Nullable<int> EtatCompteur_ID { get; set; }
        public Nullable<System.Guid> CapotMoteur_ID_Scelle1 { get; set; }
        public Nullable<System.Guid> CapotMoteur_ID_Scelle2 { get; set; }
        public Nullable<System.Guid> CapotMoteur_ID_Scelle3 { get; set; }
        public Nullable<System.Guid> Cache_Scelle { get; set; }
        public string MARQUE { get; set; }
        public string ANNEEFAB { get; set; }
        public string FONCTIONNEMENT { get; set; }
        public string TYPE_COMPTEUR { get; set; }
        public Nullable<byte> CADRAN { get; set; }
        public Nullable<int> FK_IDCALIBRECOMPTEUR { get; set; }
        public int FK_IDMARQUECOMPTEUR { get; set; }
        public Nullable<int> FK_IDTYPECOMPTEUR { get; set; }
        public string USERCREATION { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public Nullable<int> FK_IDPRODUIT { get; set; }
        public int PK_ID { get; set; }
    
        public virtual CALIBRECOMPTEUR CALIBRECOMPTEUR { get; set; }
        public virtual ICollection<MAGASINVIRTUEL> MAGASINVIRTUEL { get; set; }
        public virtual MARQUECOMPTEUR MARQUECOMPTEUR { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
        public virtual TYPECOMPTEUR TYPECOMPTEUR { get; set; }
        public virtual Scelles Scelles { get; set; }
        public virtual Scelles Scelles1 { get; set; }
        public virtual Scelles Scelles2 { get; set; }
        public virtual Scelles Scelles3 { get; set; }
    }
}
