//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbDetailRetourScelles
    {
        public System.Guid Id_DetailRetour { get; set; }
        public System.Guid Id_Retour { get; set; }
        public Nullable<int> Motif_Retour { get; set; }
        public Nullable<System.Guid> Id_Scelle { get; set; }
    }
}
