//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbElementsLotDeControleBTA
    {
        public System.Guid Lot_ID { get; set; }
        public string Contrat_ID { get; set; }
        public System.DateTime DateSelection { get; set; }
        public System.DateTime DateAffectationLot { get; set; }
        public Nullable<System.Guid> ResultatControle_ID { get; set; }
        public int Methode_ID { get; set; }
        public int Debut_PerAA { get; set; }
        public int Debut_PerMM { get; set; }
        public int Fin_PerAA { get; set; }
        public int Fin_PerMM { get; set; }
        public double Difference { get; set; }
        public Nullable<double> C_MChuteConso_ConsoEnChute_Valeur { get; set; }
        public Nullable<int> C_MChuteConso_ConsoEnChute_PerAA { get; set; }
        public Nullable<int> C_MChuteConso_ConsoEnChute_PerMM { get; set; }
        public Nullable<int> C_MChuteConso_ConsoPrecedente_PerAA { get; set; }
        public Nullable<int> C_MChuteConso_ConsoPrecedente_PerMM { get; set; }
        public Nullable<double> C_MConsoFaible_ConsoJournaliereAttendue { get; set; }
        public Nullable<double> C_MConsoFaible_ConsommationFacturee { get; set; }
        public Nullable<int> C_MConsoFaible_NbreJoursDeConso { get; set; }
    
        public virtual tbLotsDeControleBTA tbLotsDeControleBTA { get; set; }
    }
}
