//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLotsDeControleBTA
    {
        public tbLotsDeControleBTA()
        {
            this.tbElementsLotDeControleBTA = new HashSet<tbElementsLotDeControleBTA>();
        }
    
        public System.Guid Lot_ID { get; set; }
        public string Libelle_Lot { get; set; }
        public int StatutLot_ID { get; set; }
        public System.Guid Campagne_ID { get; set; }
        public System.DateTime DateCreation { get; set; }
        public string MatriculeAgentCreation { get; set; }
        public Nullable<System.DateTime> DateFermeture { get; set; }
        public string MatriculeAgentControleur { get; set; }
        public int NbreElementsDuLot { get; set; }
        public Nullable<int> Critere_TypeClient { get; set; }
        public Nullable<int> Critere_GroupeDeFacturation { get; set; }
        public string Critere_TypeTarif { get; set; }
        public Nullable<int> Critere_TypeCompteur { get; set; }
        public Nullable<int> Critere_IdTournee { get; set; }
    
        public virtual tbCampagnesControleBTA tbCampagnesControleBTA { get; set; }
        public virtual ICollection<tbElementsLotDeControleBTA> tbElementsLotDeControleBTA { get; set; }
    }
}
