//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbLotMagasinGeneral
    {
        public string Id_LotMagasinGeneral { get; set; }
        public System.DateTime DateReception { get; set; }
        public Nullable<int> Matricule_AgentReception { get; set; }
        public string Numero_depart { get; set; }
        public string Numero_fin { get; set; }
        public Nullable<int> Nbre_Scelles { get; set; }
        public Nullable<int> StatutLot_ID { get; set; }
        public Nullable<int> Origine_ID { get; set; }
        public Nullable<int> Couleur_ID { get; set; }
        public Nullable<int> Fournisseur_ID { get; set; }
        public Nullable<System.DateTime> Date_DerniereModif { get; set; }
        public Nullable<int> Matricule_AgentDerniereModif { get; set; }
        public Nullable<System.Guid> Id_Affectation { get; set; }
        public Nullable<int> CodeCentre { get; set; }
        public Nullable<int> Activite_ID { get; set; }
    
        public virtual CENTRE CENTRE { get; set; }
        public virtual RefActivite RefActivite { get; set; }
        public virtual RefCouleurlot RefCouleurlot { get; set; }
        public virtual RefFournisseurs RefFournisseurs { get; set; }
        public virtual RefOrigineScelle RefOrigineScelle { get; set; }
        public virtual RefStatutLotMagasinGeneral RefStatutLotMagasinGeneral { get; set; }
    }
}
