//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRemiseScelles
    {
        public tbRemiseScelles()
        {
            this.tbDetailRemiseScelles = new HashSet<tbDetailRemiseScelles>();
        }
    
        public System.Guid Id_Remise { get; set; }
        public System.DateTime Date_Remise { get; set; }
        public int Matricule_User { get; set; }
        public int Matricule_Receiver { get; set; }
        public int Motif_ID { get; set; }
        public Nullable<int> Nbre_Scelles { get; set; }
        public string CodeExploitation { get; set; }
        public Nullable<int> TypeRemise { get; set; }
        public Nullable<int> CodeCentre { get; set; }
    
        public virtual CENTRE CENTRE { get; set; }
        public virtual RefMotif RefMotif { get; set; }
        public virtual ICollection<tbDetailRemiseScelles> tbDetailRemiseScelles { get; set; }
    }
}
