//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOURNEE
    {
        public TOURNEE()
        {
            this.AG = new HashSet<AG>();
            this.DAG = new HashSet<DAG>();
            this.DETAILCAMPAGNE = new HashSet<DETAILCAMPAGNE>();
            this.DETAILCAMPAGNEPRENCONTENTIEUX = new HashSet<DETAILCAMPAGNEPRENCONTENTIEUX>();
            this.DETAILCAMPAGNEPRENCONTENTIEUX1 = new HashSet<DETAILCAMPAGNEPRENCONTENTIEUX>();
            this.ENTFAC = new HashSet<ENTFAC>();
            this.EVENEMENT = new HashSet<EVENEMENT>();
            this.LOTRI = new HashSet<LOTRI>();
            this.PAGERI = new HashSet<PAGERI>();
            this.PAGISOL = new HashSet<PAGISOL>();
            this.TOURNEEPIA = new HashSet<TOURNEEPIA>();
            this.TOURNEERELEVEUR = new HashSet<TOURNEERELEVEUR>();
            this.FAC_ENTFAC = new HashSet<FAC_ENTFAC>();
        }
    
        public string CENTRE { get; set; }
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public string LOCALISATION { get; set; }
        public string PRIORITE { get; set; }
        public string USERCREATION { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int PK_ID { get; set; }
        public Nullable<bool> SUPPRIMER { get; set; }
        public int FK_IDCENTRE { get; set; }
        public Nullable<int> FK_IDLOCALISATION { get; set; }
    
        public virtual ICollection<AG> AG { get; set; }
        public virtual CENTRE CENTRE1 { get; set; }
        public virtual ICollection<DAG> DAG { get; set; }
        public virtual ICollection<DETAILCAMPAGNE> DETAILCAMPAGNE { get; set; }
        public virtual ICollection<DETAILCAMPAGNEPRENCONTENTIEUX> DETAILCAMPAGNEPRENCONTENTIEUX { get; set; }
        public virtual ICollection<DETAILCAMPAGNEPRENCONTENTIEUX> DETAILCAMPAGNEPRENCONTENTIEUX1 { get; set; }
        public virtual ICollection<ENTFAC> ENTFAC { get; set; }
        public virtual ICollection<EVENEMENT> EVENEMENT { get; set; }
        public virtual LOCALISATION LOCALISATION1 { get; set; }
        public virtual ICollection<LOTRI> LOTRI { get; set; }
        public virtual ICollection<PAGERI> PAGERI { get; set; }
        public virtual ICollection<PAGISOL> PAGISOL { get; set; }
        public virtual ICollection<TOURNEEPIA> TOURNEEPIA { get; set; }
        public virtual ICollection<TOURNEERELEVEUR> TOURNEERELEVEUR { get; set; }
        public virtual ICollection<FAC_ENTFAC> FAC_ENTFAC { get; set; }
    }
}
