//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPECLIENT
    {
        public TYPECLIENT()
        {
            this.CATEGORIECLIENT_TYPECLIENT = new HashSet<CATEGORIECLIENT_TYPECLIENT>();
            this.CLIENT = new HashSet<CLIENT>();
            this.DCLIENT = new HashSet<DCLIENT>();
        }
    
        public int PK_ID { get; set; }
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
    
        public virtual ICollection<CATEGORIECLIENT_TYPECLIENT> CATEGORIECLIENT_TYPECLIENT { get; set; }
        public virtual ICollection<CLIENT> CLIENT { get; set; }
        public virtual ICollection<DCLIENT> DCLIENT { get; set; }
    }
}
