//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPEBRANCHEMENTPARPRODUIT
    {
        public int PK_ID { get; set; }
        public int FK_IDTYPEBRANCHEMENT { get; set; }
        public int FK_IDPRODUIT { get; set; }
    
        public virtual PRODUIT PRODUIT { get; set; }
        public virtual TYPEBRANCHEMENT TYPEBRANCHEMENT { get; set; }
    }
}
