//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPEMATERIEL
    {
        public TYPEMATERIEL()
        {
            this.MATERIELDEVIS = new HashSet<MATERIELDEVIS>();
        }
    
        public int PK_ID { get; set; }
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<int> FK_IDPRODUIT { get; set; }
    
        public virtual ICollection<MATERIELDEVIS> MATERIELDEVIS { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
