//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPETARIF
    {
        public TYPETARIF()
        {
            this.ABON = new HashSet<ABON>();
            this.COUTDEMANDE = new HashSet<COUTDEMANDE>();
            this.DABON = new HashSet<DABON>();
            this.TYPETARIFPARCATEGORIE = new HashSet<TYPETARIFPARCATEGORIE>();
            this.TYPETARIFPARREGLAGECOMPTEUR = new HashSet<TYPETARIFPARREGLAGECOMPTEUR>();
        }
    
        public string CODE { get; set; }
        public string PRODUIT { get; set; }
        public string LIBELLE { get; set; }
        public string USERCREATION { get; set; }
        public System.DateTime DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string USERMODIFICATION { get; set; }
        public int PK_ID { get; set; }
        public int FK_IDPRODUIT { get; set; }
    
        public virtual ICollection<ABON> ABON { get; set; }
        public virtual ICollection<COUTDEMANDE> COUTDEMANDE { get; set; }
        public virtual ICollection<DABON> DABON { get; set; }
        public virtual PRODUIT PRODUIT1 { get; set; }
        public virtual ICollection<TYPETARIFPARCATEGORIE> TYPETARIFPARCATEGORIE { get; set; }
        public virtual ICollection<TYPETARIFPARREGLAGECOMPTEUR> TYPETARIFPARREGLAGECOMPTEUR { get; set; }
    }
}
