//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPECOUPURE
    {
        public TYPECOUPURE()
        {
            this.DETAILCAMPAGNE = new HashSet<DETAILCAMPAGNE>();
            this.INDEXCAMPAGNE = new HashSet<INDEXCAMPAGNE>();
            this.INDEXCAMPAGNESGC = new HashSet<INDEXCAMPAGNESGC>();
        }
    
        public int PK_ID { get; set; }
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<int> FK_IDCOPER { get; set; }
        public Nullable<decimal> COUT { get; set; }
    
        public virtual COPER COPER { get; set; }
        public virtual ICollection<DETAILCAMPAGNE> DETAILCAMPAGNE { get; set; }
        public virtual ICollection<INDEXCAMPAGNE> INDEXCAMPAGNE { get; set; }
        public virtual ICollection<INDEXCAMPAGNESGC> INDEXCAMPAGNESGC { get; set; }
    }
}
