//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DASHBORDDEMANDE
    {
        public int IDETAPE { get; set; }
        public string NOM { get; set; }
        public Nullable<int> FK_IDETAPEACTUELLE { get; set; }
        public System.Guid IDCIRCUIT { get; set; }
        public Nullable<int> NOMBREDEMANDE { get; set; }
        public System.Guid FK_IDGROUPEVALIDATIOIN { get; set; }
        public System.Guid FK_IDWORKFLOW { get; set; }
        public System.Guid FK_IDOPERATION { get; set; }
        public int FK_IDCENTRE { get; set; }
        public int ORDRE { get; set; }
        public int FK_IDETAPE { get; set; }
        public Nullable<int> DUREE { get; set; }
        public Nullable<int> ALERTE { get; set; }
        public string CONTROLEETAPE { get; set; }
        public Nullable<int> FK_IDMENU { get; set; }
        public string WORKFLOWNAME { get; set; }
        public string NOMOPERATION { get; set; }
        public Nullable<bool> IS_TRAITEMENT_LOT { get; set; }
        public Nullable<System.Guid> FK_IDDEMANDE { get; set; }
        public Nullable<int> STATUTDEMANDE { get; set; }
    }
}
