//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCONFIGURATIONWORKFLOWCENTRE
    {
        public System.Guid PK_ID { get; set; }
        public string WORKFLOWNAME { get; set; }
        public System.Guid OPERATIONID { get; set; }
        public string NOM { get; set; }
        public string FORMULAIRE { get; set; }
        public Nullable<int> FK_IDFORMULAIRE { get; set; }
        public string CODECENTRE { get; set; }
        public string LIBELLE { get; set; }
        public int CENTREID { get; set; }
        public int FK_IDCODESITE { get; set; }
        public string CODESITE { get; set; }
    }
}
