//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Silverlight.Resources.Facturation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galatee.Silverlight.Resources.Facturation.Langue", typeof(Langue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factures domicilés.
        /// </summary>
        internal static string Bank_acount_invoices {
            get {
                return ResourceManager.GetString("Bank_acount_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        internal static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Btn_cancel {
            get {
                return ResourceManager.GetString("Btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désélectionner tout.
        /// </summary>
        internal static string btn_DéselectionTout {
            get {
                return ResourceManager.GetString("btn_DéselectionTout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        internal static string Btn_enregistrer {
            get {
                return ResourceManager.GetString("Btn_enregistrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        internal static string Btn_format {
            get {
                return ResourceManager.GetString("Btn_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimante.
        /// </summary>
        internal static string Btn_imprimante {
            get {
                return ResourceManager.GetString("Btn_imprimante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer.
        /// </summary>
        internal static string Btn_lancer {
            get {
                return ResourceManager.GetString("Btn_lancer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Période.
        /// </summary>
        internal static string Btn_periode {
            get {
                return ResourceManager.GetString("Btn_periode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procuration.
        /// </summary>
        internal static string Btn_procuration {
            get {
                return ResourceManager.GetString("Btn_procuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner tout.
        /// </summary>
        internal static string btn_SélectionTout {
            get {
                return ResourceManager.GetString("btn_SélectionTout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string Btn_supprimer {
            get {
                return ResourceManager.GetString("Btn_supprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition par tournée.
        /// </summary>
        internal static string Chk_print_zone {
            get {
                return ResourceManager.GetString("Chk_print_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprise sur client.
        /// </summary>
        internal static string Chk_reprise_client {
            get {
                return ResourceManager.GetString("Chk_reprise_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop sur client.
        /// </summary>
        internal static string Chk_stop_client {
            get {
                return ResourceManager.GetString("Chk_stop_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bordereaux detaillé.
        /// </summary>
        internal static string Details_list {
            get {
                return ResourceManager.GetString("Details_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factures groupées.
        /// </summary>
        internal static string Groupes_invoices {
            get {
                return ResourceManager.GetString("Groupes_invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facture.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string Lbl_center1 {
            get {
                return ResourceManager.GetString("Lbl_center1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string Lbl_centre {
            get {
                return ResourceManager.GetString("Lbl_centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centre.
        /// </summary>
        internal static string Lbl_centre2 {
            get {
                return ResourceManager.GetString("Lbl_centre2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtre d&apos;édition.
        /// </summary>
        internal static string Lbl_filtre_edition {
            get {
                return ResourceManager.GetString("Lbl_filtre_edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depuis regroupement.
        /// </summary>
        internal static string Lbl_from {
            get {
                return ResourceManager.GetString("Lbl_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impression.
        /// </summary>
        internal static string Lbl_impression {
            get {
                return ResourceManager.GetString("Lbl_impression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprise d&apos;édition.
        /// </summary>
        internal static string Lbl_reprise_edition {
            get {
                return ResourceManager.GetString("Lbl_reprise_edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to à.
        /// </summary>
        internal static string Lbl_to {
            get {
                return ResourceManager.GetString("Lbl_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tri par.
        /// </summary>
        internal static string Lbl_tri {
            get {
                return ResourceManager.GetString("Lbl_tri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jusqu&apos;à.
        /// </summary>
        internal static string Lbl_until {
            get {
                return ResourceManager.GetString("Lbl_until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournée.
        /// </summary>
        internal static string Lbl_zone {
            get {
                return ResourceManager.GetString("Lbl_zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturation.
        /// </summary>
        internal static string LibelleModule {
            get {
                return ResourceManager.GetString("LibelleModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bordereaux simplifié.
        /// </summary>
        internal static string List_simplified {
            get {
                return ResourceManager.GetString("List_simplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date d&apos;exigibilité est trop courte.
        /// </summary>
        internal static string MsgDateExigibiliteTropCourte {
            get {
                return ResourceManager.GetString("MsgDateExigibiliteTropCourte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date d&apos;exigibilité est trop longue.
        /// </summary>
        internal static string MsgDateExigibiliteTropLong {
            get {
                return ResourceManager.GetString("MsgDateExigibiliteTropLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la défacturation.
        /// </summary>
        internal static string msgDefacturation {
            get {
                return ResourceManager.GetString("msgDefacturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une simulation existe sur ce lot,
        ///elle va ètre détruite ..
        /// </summary>
        internal static string msgDestructionSimulation {
            get {
                return ResourceManager.GetString("msgDestructionSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de mise à jours du lot.
        /// </summary>
        internal static string msgErreurMaj {
            get {
                return ResourceManager.GetString("msgErreurMaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est produite lors de la facturation.
        /// </summary>
        internal static string msgErrorFact {
            get {
                return ResourceManager.GetString("msgErrorFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturation validée.
        /// </summary>
        internal static string msgFacturationConfirmee {
            get {
                return ResourceManager.GetString("msgFacturationConfirmee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de défacturation rejétée.
        /// </summary>
        internal static string msgRejetDefacturation {
            get {
                return ResourceManager.GetString("msgRejetDefacturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer la suppression de la simulation.
        /// </summary>
        internal static string msgSuppressionSimulation {
            get {
                return ResourceManager.GetString("msgSuppressionSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition domicilées bancaires.
        /// </summary>
        internal static string Print_bank {
            get {
                return ResourceManager.GetString("Print_bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition de clients regroupés.
        /// </summary>
        internal static string Print_client_group {
            get {
                return ResourceManager.GetString("Print_client_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format d&apos;édition.
        /// </summary>
        internal static string Print_format {
            get {
                return ResourceManager.GetString("Print_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition de lot.
        /// </summary>
        internal static string Print_lot {
            get {
                return ResourceManager.GetString("Print_lot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteristiques de l&apos;impresion.
        /// </summary>
        internal static string Print_spec {
            get {
                return ResourceManager.GetString("Print_spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type d&apos;edition.
        /// </summary>
        internal static string Print_type {
            get {
                return ResourceManager.GetString("Print_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition anomalies.
        /// </summary>
        internal static string Printings_error {
            get {
                return ResourceManager.GetString("Printings_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Rdb_client {
            get {
                return ResourceManager.GetString("Rdb_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tournée.
        /// </summary>
        internal static string Rdb_tournee {
            get {
                return ResourceManager.GetString("Rdb_tournee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recapitulatif uniquement.
        /// </summary>
        internal static string Recap_only {
            get {
                return ResourceManager.GetString("Recap_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des lots.
        /// </summary>
        internal static string titreListeLot {
            get {
                return ResourceManager.GetString("titreListeLot", resourceCulture);
            }
        }
    }
}
