//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Silverlight.Web.ServiceEservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CsEnvoiMail", Namespace="http://schemas.datacontract.org/2004/07/Galatee.Structure")]
    [System.SerializableAttribute()]
    public partial class CsEnvoiMail : Galatee.Silverlight.Web.ServiceEservice.CsPrint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string centreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal montantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numfactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ordreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string periodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomClient {
            get {
                return this.NomClientField;
            }
            set {
                if ((object.ReferenceEquals(this.NomClientField, value) != true)) {
                    this.NomClientField = value;
                    this.RaisePropertyChanged("NomClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string centre {
            get {
                return this.centreField;
            }
            set {
                if ((object.ReferenceEquals(this.centreField, value) != true)) {
                    this.centreField = value;
                    this.RaisePropertyChanged("centre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string client {
            get {
                return this.clientField;
            }
            set {
                if ((object.ReferenceEquals(this.clientField, value) != true)) {
                    this.clientField = value;
                    this.RaisePropertyChanged("client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal montant {
            get {
                return this.montantField;
            }
            set {
                if ((this.montantField.Equals(value) != true)) {
                    this.montantField = value;
                    this.RaisePropertyChanged("montant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numfact {
            get {
                return this.numfactField;
            }
            set {
                if ((object.ReferenceEquals(this.numfactField, value) != true)) {
                    this.numfactField = value;
                    this.RaisePropertyChanged("numfact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ordre {
            get {
                return this.ordreField;
            }
            set {
                if ((object.ReferenceEquals(this.ordreField, value) != true)) {
                    this.ordreField = value;
                    this.RaisePropertyChanged("ordre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string periode {
            get {
                return this.periodeField;
            }
            set {
                if ((object.ReferenceEquals(this.periodeField, value) != true)) {
                    this.periodeField = value;
                    this.RaisePropertyChanged("periode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CsPrint", Namespace="http://schemas.datacontract.org/2004/07/Galatee.Structure")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Galatee.Silverlight.Web.ServiceEservice.CsFactureClient))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Galatee.Silverlight.Web.ServiceEservice.CsEnvoiMail))]
    public partial class CsPrint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CsFactureClient", Namespace="http://schemas.datacontract.org/2004/07/Galatee.Structure")]
    [System.SerializableAttribute()]
    public partial class CsFactureClient : Galatee.Silverlight.Web.ServiceEservice.CsPrint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adrmand1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Adrmand2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AncienReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BanqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BarPrixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BureauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CadrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CatcliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodconsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeProfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommuneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComprueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ConsoFacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CposField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DelajuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenAbonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenmandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DevPreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DfacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiametreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DresAbonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMAILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ExigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FactureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuichetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ISFACTUREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ISSMSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleCategField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleRegcliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LibelleTrancheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LienFacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LotriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModepField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoisComptaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NatureClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NbFacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomAbonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomrueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumrueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdTourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdreAffichageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeriodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PorteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProduitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuartierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceATMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegcliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegeditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RibField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SoldeTotFTTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TELEPHONEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopMajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotFTTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotFTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotFhtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotRedHTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotRedTTCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotRedTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotajuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalNonarrondiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TourneeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrancheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateExigeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AIndex {
            get {
                return this.AIndexField;
            }
            set {
                if ((this.AIndexField.Equals(value) != true)) {
                    this.AIndexField = value;
                    this.RaisePropertyChanged("AIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adrmand1 {
            get {
                return this.Adrmand1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adrmand1Field, value) != true)) {
                    this.Adrmand1Field = value;
                    this.RaisePropertyChanged("Adrmand1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adrmand2 {
            get {
                return this.Adrmand2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Adrmand2Field, value) != true)) {
                    this.Adrmand2Field = value;
                    this.RaisePropertyChanged("Adrmand2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ag {
            get {
                return this.AgField;
            }
            set {
                if ((object.ReferenceEquals(this.AgField, value) != true)) {
                    this.AgField = value;
                    this.RaisePropertyChanged("Ag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AncienReport {
            get {
                return this.AncienReportField;
            }
            set {
                if ((this.AncienReportField.Equals(value) != true)) {
                    this.AncienReportField = value;
                    this.RaisePropertyChanged("AncienReport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banque {
            get {
                return this.BanqueField;
            }
            set {
                if ((object.ReferenceEquals(this.BanqueField, value) != true)) {
                    this.BanqueField = value;
                    this.RaisePropertyChanged("Banque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BarPrix {
            get {
                return this.BarPrixField;
            }
            set {
                if ((this.BarPrixField.Equals(value) != true)) {
                    this.BarPrixField = value;
                    this.RaisePropertyChanged("BarPrix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bureau {
            get {
                return this.BureauField;
            }
            set {
                if ((object.ReferenceEquals(this.BureauField, value) != true)) {
                    this.BureauField = value;
                    this.RaisePropertyChanged("Bureau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cadr {
            get {
                return this.CadrField;
            }
            set {
                if ((object.ReferenceEquals(this.CadrField, value) != true)) {
                    this.CadrField = value;
                    this.RaisePropertyChanged("Cadr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Catcli {
            get {
                return this.CatcliField;
            }
            set {
                if ((object.ReferenceEquals(this.CatcliField, value) != true)) {
                    this.CatcliField = value;
                    this.RaisePropertyChanged("Catcli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Centre {
            get {
                return this.CentreField;
            }
            set {
                if ((object.ReferenceEquals(this.CentreField, value) != true)) {
                    this.CentreField = value;
                    this.RaisePropertyChanged("Centre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codconso {
            get {
                return this.CodconsoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodconsoField, value) != true)) {
                    this.CodconsoField = value;
                    this.RaisePropertyChanged("Codconso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeProfil {
            get {
                return this.CodeProfilField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeProfilField, value) != true)) {
                    this.CodeProfilField = value;
                    this.RaisePropertyChanged("CodeProfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commune {
            get {
                return this.CommuneField;
            }
            set {
                if ((object.ReferenceEquals(this.CommuneField, value) != true)) {
                    this.CommuneField = value;
                    this.RaisePropertyChanged("Commune");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comprue {
            get {
                return this.ComprueField;
            }
            set {
                if ((object.ReferenceEquals(this.ComprueField, value) != true)) {
                    this.ComprueField = value;
                    this.RaisePropertyChanged("Comprue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Compte {
            get {
                return this.CompteField;
            }
            set {
                if ((object.ReferenceEquals(this.CompteField, value) != true)) {
                    this.CompteField = value;
                    this.RaisePropertyChanged("Compte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Compteur {
            get {
                return this.CompteurField;
            }
            set {
                if ((object.ReferenceEquals(this.CompteurField, value) != true)) {
                    this.CompteurField = value;
                    this.RaisePropertyChanged("Compteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ConsoFac {
            get {
                return this.ConsoFacField;
            }
            set {
                if ((this.ConsoFacField.Equals(value) != true)) {
                    this.ConsoFacField = value;
                    this.RaisePropertyChanged("ConsoFac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Coper {
            get {
                return this.CoperField;
            }
            set {
                if ((object.ReferenceEquals(this.CoperField, value) != true)) {
                    this.CoperField = value;
                    this.RaisePropertyChanged("Coper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cpos {
            get {
                return this.CposField;
            }
            set {
                if ((object.ReferenceEquals(this.CposField, value) != true)) {
                    this.CposField = value;
                    this.RaisePropertyChanged("Cpos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Delaju {
            get {
                return this.DelajuField;
            }
            set {
                if ((this.DelajuField.Equals(value) != true)) {
                    this.DelajuField = value;
                    this.RaisePropertyChanged("Delaju");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DenAbon {
            get {
                return this.DenAbonField;
            }
            set {
                if ((object.ReferenceEquals(this.DenAbonField, value) != true)) {
                    this.DenAbonField = value;
                    this.RaisePropertyChanged("DenAbon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denmand {
            get {
                return this.DenmandField;
            }
            set {
                if ((object.ReferenceEquals(this.DenmandField, value) != true)) {
                    this.DenmandField = value;
                    this.RaisePropertyChanged("Denmand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DevPre {
            get {
                return this.DevPreField;
            }
            set {
                if ((object.ReferenceEquals(this.DevPreField, value) != true)) {
                    this.DevPreField = value;
                    this.RaisePropertyChanged("DevPre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dfac {
            get {
                return this.DfacField;
            }
            set {
                if ((object.ReferenceEquals(this.DfacField, value) != true)) {
                    this.DfacField = value;
                    this.RaisePropertyChanged("Dfac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Diametre {
            get {
                return this.DiametreField;
            }
            set {
                if ((object.ReferenceEquals(this.DiametreField, value) != true)) {
                    this.DiametreField = value;
                    this.RaisePropertyChanged("Diametre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dr {
            get {
                return this.DrField;
            }
            set {
                if ((object.ReferenceEquals(this.DrField, value) != true)) {
                    this.DrField = value;
                    this.RaisePropertyChanged("Dr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DresAbon {
            get {
                return this.DresAbonField;
            }
            set {
                if ((this.DresAbonField.Equals(value) != true)) {
                    this.DresAbonField = value;
                    this.RaisePropertyChanged("DresAbon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMAIL {
            get {
                return this.EMAILField;
            }
            set {
                if ((object.ReferenceEquals(this.EMAILField, value) != true)) {
                    this.EMAILField = value;
                    this.RaisePropertyChanged("EMAIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Email")]
        public string Email1 {
            get {
                return this.Email1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Email1Field, value) != true)) {
                    this.Email1Field = value;
                    this.RaisePropertyChanged("Email1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Etage {
            get {
                return this.EtageField;
            }
            set {
                if ((object.ReferenceEquals(this.EtageField, value) != true)) {
                    this.EtageField = value;
                    this.RaisePropertyChanged("Etage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Exig {
            get {
                return this.ExigField;
            }
            set {
                if ((this.ExigField.Equals(value) != true)) {
                    this.ExigField = value;
                    this.RaisePropertyChanged("Exig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Facture {
            get {
                return this.FactureField;
            }
            set {
                if ((object.ReferenceEquals(this.FactureField, value) != true)) {
                    this.FactureField = value;
                    this.RaisePropertyChanged("Facture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guichet {
            get {
                return this.GuichetField;
            }
            set {
                if ((object.ReferenceEquals(this.GuichetField, value) != true)) {
                    this.GuichetField = value;
                    this.RaisePropertyChanged("Guichet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ISFACTURE {
            get {
                return this.ISFACTUREField;
            }
            set {
                if ((this.ISFACTUREField.Equals(value) != true)) {
                    this.ISFACTUREField = value;
                    this.RaisePropertyChanged("ISFACTURE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ISSMS {
            get {
                return this.ISSMSField;
            }
            set {
                if ((this.ISSMSField.Equals(value) != true)) {
                    this.ISSMSField = value;
                    this.RaisePropertyChanged("ISSMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jet {
            get {
                return this.JetField;
            }
            set {
                if ((object.ReferenceEquals(this.JetField, value) != true)) {
                    this.JetField = value;
                    this.RaisePropertyChanged("Jet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LibelleCateg {
            get {
                return this.LibelleCategField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleCategField, value) != true)) {
                    this.LibelleCategField = value;
                    this.RaisePropertyChanged("LibelleCateg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LibelleProduit {
            get {
                return this.LibelleProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleProduitField, value) != true)) {
                    this.LibelleProduitField = value;
                    this.RaisePropertyChanged("LibelleProduit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LibelleRegcli {
            get {
                return this.LibelleRegcliField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleRegcliField, value) != true)) {
                    this.LibelleRegcliField = value;
                    this.RaisePropertyChanged("LibelleRegcli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LibelleTranche {
            get {
                return this.LibelleTrancheField;
            }
            set {
                if ((object.ReferenceEquals(this.LibelleTrancheField, value) != true)) {
                    this.LibelleTrancheField = value;
                    this.RaisePropertyChanged("LibelleTranche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LienFac {
            get {
                return this.LienFacField;
            }
            set {
                if ((object.ReferenceEquals(this.LienFacField, value) != true)) {
                    this.LienFacField = value;
                    this.RaisePropertyChanged("LienFac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lotri {
            get {
                return this.LotriField;
            }
            set {
                if ((object.ReferenceEquals(this.LotriField, value) != true)) {
                    this.LotriField = value;
                    this.RaisePropertyChanged("Lotri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mes {
            get {
                return this.MesField;
            }
            set {
                if ((object.ReferenceEquals(this.MesField, value) != true)) {
                    this.MesField = value;
                    this.RaisePropertyChanged("Mes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modep {
            get {
                return this.ModepField;
            }
            set {
                if ((object.ReferenceEquals(this.ModepField, value) != true)) {
                    this.ModepField = value;
                    this.RaisePropertyChanged("Modep");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoisCompta {
            get {
                return this.MoisComptaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoisComptaField, value) != true)) {
                    this.MoisComptaField = value;
                    this.RaisePropertyChanged("MoisCompta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NIndex {
            get {
                return this.NIndexField;
            }
            set {
                if ((this.NIndexField.Equals(value) != true)) {
                    this.NIndexField = value;
                    this.RaisePropertyChanged("NIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nature {
            get {
                return this.NatureField;
            }
            set {
                if ((object.ReferenceEquals(this.NatureField, value) != true)) {
                    this.NatureField = value;
                    this.RaisePropertyChanged("Nature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NatureClient {
            get {
                return this.NatureClientField;
            }
            set {
                if ((object.ReferenceEquals(this.NatureClientField, value) != true)) {
                    this.NatureClientField = value;
                    this.RaisePropertyChanged("NatureClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NbFac {
            get {
                return this.NbFacField;
            }
            set {
                if ((object.ReferenceEquals(this.NbFacField, value) != true)) {
                    this.NbFacField = value;
                    this.RaisePropertyChanged("NbFac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomAbon {
            get {
                return this.NomAbonField;
            }
            set {
                if ((object.ReferenceEquals(this.NomAbonField, value) != true)) {
                    this.NomAbonField = value;
                    this.RaisePropertyChanged("NomAbon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nommand {
            get {
                return this.NommandField;
            }
            set {
                if ((object.ReferenceEquals(this.NommandField, value) != true)) {
                    this.NommandField = value;
                    this.RaisePropertyChanged("Nommand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nomrue {
            get {
                return this.NomrueField;
            }
            set {
                if ((object.ReferenceEquals(this.NomrueField, value) != true)) {
                    this.NomrueField = value;
                    this.RaisePropertyChanged("Nomrue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numrue {
            get {
                return this.NumrueField;
            }
            set {
                if ((object.ReferenceEquals(this.NumrueField, value) != true)) {
                    this.NumrueField = value;
                    this.RaisePropertyChanged("Numrue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdTour {
            get {
                return this.OrdTourField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdTourField, value) != true)) {
                    this.OrdTourField = value;
                    this.RaisePropertyChanged("OrdTour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ordre {
            get {
                return this.OrdreField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdreField, value) != true)) {
                    this.OrdreField = value;
                    this.RaisePropertyChanged("Ordre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdreAffichage {
            get {
                return this.OrdreAffichageField;
            }
            set {
                if ((this.OrdreAffichageField.Equals(value) != true)) {
                    this.OrdreAffichageField = value;
                    this.RaisePropertyChanged("OrdreAffichage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Periode {
            get {
                return this.PeriodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodeField, value) != true)) {
                    this.PeriodeField = value;
                    this.RaisePropertyChanged("Periode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Porte {
            get {
                return this.PorteField;
            }
            set {
                if ((object.ReferenceEquals(this.PorteField, value) != true)) {
                    this.PorteField = value;
                    this.RaisePropertyChanged("Porte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Produit {
            get {
                return this.ProduitField;
            }
            set {
                if ((object.ReferenceEquals(this.ProduitField, value) != true)) {
                    this.ProduitField = value;
                    this.RaisePropertyChanged("Produit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantite {
            get {
                return this.QuantiteField;
            }
            set {
                if ((this.QuantiteField.Equals(value) != true)) {
                    this.QuantiteField = value;
                    this.RaisePropertyChanged("Quantite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quartier {
            get {
                return this.QuartierField;
            }
            set {
                if ((object.ReferenceEquals(this.QuartierField, value) != true)) {
                    this.QuartierField = value;
                    this.RaisePropertyChanged("Quartier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceATM {
            get {
                return this.ReferenceATMField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceATMField, value) != true)) {
                    this.ReferenceATMField = value;
                    this.RaisePropertyChanged("ReferenceATM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regcli {
            get {
                return this.RegcliField;
            }
            set {
                if ((object.ReferenceEquals(this.RegcliField, value) != true)) {
                    this.RegcliField = value;
                    this.RaisePropertyChanged("Regcli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Regedit {
            get {
                return this.RegeditField;
            }
            set {
                if ((object.ReferenceEquals(this.RegeditField, value) != true)) {
                    this.RegeditField = value;
                    this.RaisePropertyChanged("Regedit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rib {
            get {
                return this.RibField;
            }
            set {
                if ((object.ReferenceEquals(this.RibField, value) != true)) {
                    this.RibField = value;
                    this.RaisePropertyChanged("Rib");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rue {
            get {
                return this.RueField;
            }
            set {
                if ((object.ReferenceEquals(this.RueField, value) != true)) {
                    this.RueField = value;
                    this.RaisePropertyChanged("Rue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secteur {
            get {
                return this.SecteurField;
            }
            set {
                if ((object.ReferenceEquals(this.SecteurField, value) != true)) {
                    this.SecteurField = value;
                    this.RaisePropertyChanged("Secteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SoldeTotFTTC {
            get {
                return this.SoldeTotFTTCField;
            }
            set {
                if ((this.SoldeTotFTTCField.Equals(value) != true)) {
                    this.SoldeTotFTTCField = value;
                    this.RaisePropertyChanged("SoldeTotFTTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TELEPHONE {
            get {
                return this.TELEPHONEField;
            }
            set {
                if ((object.ReferenceEquals(this.TELEPHONEField, value) != true)) {
                    this.TELEPHONEField = value;
                    this.RaisePropertyChanged("TELEPHONE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TopMaj {
            get {
                return this.TopMajField;
            }
            set {
                if ((object.ReferenceEquals(this.TopMajField, value) != true)) {
                    this.TopMajField = value;
                    this.RaisePropertyChanged("TopMaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tope {
            get {
                return this.TopeField;
            }
            set {
                if ((object.ReferenceEquals(this.TopeField, value) != true)) {
                    this.TopeField = value;
                    this.RaisePropertyChanged("Tope");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotFTTC {
            get {
                return this.TotFTTCField;
            }
            set {
                if ((this.TotFTTCField.Equals(value) != true)) {
                    this.TotFTTCField = value;
                    this.RaisePropertyChanged("TotFTTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotFTax {
            get {
                return this.TotFTaxField;
            }
            set {
                if ((this.TotFTaxField.Equals(value) != true)) {
                    this.TotFTaxField = value;
                    this.RaisePropertyChanged("TotFTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotFht {
            get {
                return this.TotFhtField;
            }
            set {
                if ((this.TotFhtField.Equals(value) != true)) {
                    this.TotFhtField = value;
                    this.RaisePropertyChanged("TotFht");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotRedHT {
            get {
                return this.TotRedHTField;
            }
            set {
                if ((this.TotRedHTField.Equals(value) != true)) {
                    this.TotRedHTField = value;
                    this.RaisePropertyChanged("TotRedHT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotRedTTC {
            get {
                return this.TotRedTTCField;
            }
            set {
                if ((this.TotRedTTCField.Equals(value) != true)) {
                    this.TotRedTTCField = value;
                    this.RaisePropertyChanged("TotRedTTC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotRedTax {
            get {
                return this.TotRedTaxField;
            }
            set {
                if ((this.TotRedTaxField.Equals(value) != true)) {
                    this.TotRedTaxField = value;
                    this.RaisePropertyChanged("TotRedTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Totaju {
            get {
                return this.TotajuField;
            }
            set {
                if ((this.TotajuField.Equals(value) != true)) {
                    this.TotajuField = value;
                    this.RaisePropertyChanged("Totaju");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalNonarrondi {
            get {
                return this.TotalNonarrondiField;
            }
            set {
                if ((this.TotalNonarrondiField.Equals(value) != true)) {
                    this.TotalNonarrondiField = value;
                    this.RaisePropertyChanged("TotalNonarrondi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tournee {
            get {
                return this.TourneeField;
            }
            set {
                if ((object.ReferenceEquals(this.TourneeField, value) != true)) {
                    this.TourneeField = value;
                    this.RaisePropertyChanged("Tournee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tranche {
            get {
                return this.TrancheField;
            }
            set {
                if ((object.ReferenceEquals(this.TrancheField, value) != true)) {
                    this.TrancheField = value;
                    this.RaisePropertyChanged("Tranche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unite {
            get {
                return this.UniteField;
            }
            set {
                if ((object.ReferenceEquals(this.UniteField, value) != true)) {
                    this.UniteField = value;
                    this.RaisePropertyChanged("Unite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateExige {
            get {
                return this.dateExigeField;
            }
            set {
                if ((object.ReferenceEquals(this.dateExigeField, value) != true)) {
                    this.dateExigeField = value;
                    this.RaisePropertyChanged("dateExige");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceEservice.IEserviceService")]
    public interface IEserviceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEserviceService/ListeDesClientPourEnvoieMail", ReplyAction="http://tempuri.org/IEserviceService/ListeDesClientPourEnvoieMailResponse")]
        System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsEnvoiMail> ListeDesClientPourEnvoieMail(string Centre, string Client, string Ordre, string periode, bool sms, bool email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEserviceService/ListeDesClientPourEnvoieMail", ReplyAction="http://tempuri.org/IEserviceService/ListeDesClientPourEnvoieMailResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsEnvoiMail>> ListeDesClientPourEnvoieMailAsync(string Centre, string Client, string Ordre, string periode, bool sms, bool email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEserviceService/EnvoyerFactures", ReplyAction="http://tempuri.org/IEserviceService/EnvoyerFacturesResponse")]
        System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsFactureClient> EnvoyerFactures(System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsEnvoiMail> facturesAEnvoyer, string key, System.Collections.Generic.Dictionary<string, string> parametresRDLC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEserviceService/EnvoyerFactures", ReplyAction="http://tempuri.org/IEserviceService/EnvoyerFacturesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsFactureClient>> EnvoyerFacturesAsync(System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsEnvoiMail> facturesAEnvoyer, string key, System.Collections.Generic.Dictionary<string, string> parametresRDLC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEserviceService/ListeDesFactures", ReplyAction="http://tempuri.org/IEserviceService/ListeDesFacturesResponse")]
        System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsFactureClient> ListeDesFactures(string centre, string client, string ordre, string periode, string numFacture);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEserviceService/ListeDesFactures", ReplyAction="http://tempuri.org/IEserviceService/ListeDesFacturesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsFactureClient>> ListeDesFacturesAsync(string centre, string client, string ordre, string periode, string numFacture);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEserviceServiceChannel : Galatee.Silverlight.Web.ServiceEservice.IEserviceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EserviceServiceClient : System.ServiceModel.ClientBase<Galatee.Silverlight.Web.ServiceEservice.IEserviceService>, Galatee.Silverlight.Web.ServiceEservice.IEserviceService {
        
        public EserviceServiceClient() {
        }
        
        public EserviceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EserviceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EserviceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EserviceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsEnvoiMail> ListeDesClientPourEnvoieMail(string Centre, string Client, string Ordre, string periode, bool sms, bool email) {
            return base.Channel.ListeDesClientPourEnvoieMail(Centre, Client, Ordre, periode, sms, email);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsEnvoiMail>> ListeDesClientPourEnvoieMailAsync(string Centre, string Client, string Ordre, string periode, bool sms, bool email) {
            return base.Channel.ListeDesClientPourEnvoieMailAsync(Centre, Client, Ordre, periode, sms, email);
        }
        
        public System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsFactureClient> EnvoyerFactures(System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsEnvoiMail> facturesAEnvoyer, string key, System.Collections.Generic.Dictionary<string, string> parametresRDLC) {
            return base.Channel.EnvoyerFactures(facturesAEnvoyer, key, parametresRDLC);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsFactureClient>> EnvoyerFacturesAsync(System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsEnvoiMail> facturesAEnvoyer, string key, System.Collections.Generic.Dictionary<string, string> parametresRDLC) {
            return base.Channel.EnvoyerFacturesAsync(facturesAEnvoyer, key, parametresRDLC);
        }
        
        public System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsFactureClient> ListeDesFactures(string centre, string client, string ordre, string periode, string numFacture) {
            return base.Channel.ListeDesFactures(centre, client, ordre, periode, numFacture);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Galatee.Silverlight.Web.ServiceEservice.CsFactureClient>> ListeDesFacturesAsync(string centre, string client, string ordre, string periode, string numFacture) {
            return base.Channel.ListeDesFacturesAsync(centre, client, ordre, periode, numFacture);
        }
    }
}
