//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.269
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Silverlight.Resources.Recouvrement
{
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Langue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Langue()
        {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galatee.Silverlight.Resources.Recouvrement.Langue", typeof(Langue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tout.
        /// </summary>
        public static string bntcategorie
        {
            get
            {
                return ResourceManager.GetString("bntcategorie", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string bntCentre
        {
            get
            {
                return ResourceManager.GetString("bntCentre", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Listez les clients.
        /// </summary>
        public static string bntCreditController
        {
            get
            {
                return ResourceManager.GetString("bntCreditController", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun.
        /// </summary>
        public static string bntzone
        {
            get
            {
                return ResourceManager.GetString("bntzone", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string btnImprimer
        {
            get
            {
                return ResourceManager.GetString("btnImprimer", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment groupe.
        /// </summary>
        public static string ckcboxExclGroupeAbon
        {
            get
            {
                return ResourceManager.GetString("ckcboxExclGroupeAbon", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paiement.
        /// </summary>
        public static string ckcboxExclTeminated
        {
            get
            {
                return ResourceManager.GetString("ckcboxExclTeminated", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reference Client.
        /// </summary>
        public static string lblAmountForRemind
        {
            get
            {
                return ResourceManager.GetString("lblAmountForRemind", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Payment multiple.
        /// </summary>
        public static string lblDueDate
        {
            get
            {
                return ResourceManager.GetString("lblDueDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résilié.
        /// </summary>
        public static string lblfromMatricule
        {
            get
            {
                return ResourceManager.GetString("lblfromMatricule", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Solde courant :.
        /// </summary>
        public static string lblRemindPeriod
        {
            get
            {
                return ResourceManager.GetString("lblRemindPeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date :.
        /// </summary>
        public static string lbltoMatricule
        {
            get
            {
                return ResourceManager.GetString("lbltoMatricule", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Versement :.
        /// </summary>
        public static string lblTotalSubscriber
        {
            get
            {
                return ResourceManager.GetString("lblTotalSubscriber", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clients Selectionnés :.
        /// </summary>
        public static string rdbtnAmountReminder
        {
            get
            {
                return ResourceManager.GetString("rdbtnAmountReminder", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Solde avant paiement :.
        /// </summary>
        public static string rdbtnDetail
        {
            get
            {
                return ResourceManager.GetString("rdbtnDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total à régler :.
        /// </summary>
        public static string rdbtnList
        {
            get
            {
                return ResourceManager.GetString("rdbtnList", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total à régler :.
        /// </summary>
        public static string rdbtnNbreDeFacture
        {
            get
            {
                return ResourceManager.GetString("rdbtnNbreDeFacture", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total à régler :.
        /// </summary>
        public static string rdbtnsheet
        {
            get
            {
                return ResourceManager.GetString("rdbtnsheet", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total à régler :.
        /// </summary>
        public static string rdbtnSummary
        {
            get
            {
                return ResourceManager.GetString("rdbtnSummary", resourceCulture);
            }
        }
    }
}
