//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Sms.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Galatee.Sms.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune caisse ouverte.
        /// </summary>
        internal static string AUCUNE_CAISSE_OUVERTE {
            get {
                return ResourceManager.GetString("AUCUNE_CAISSE_OUVERTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caisse inexistante.
        /// </summary>
        internal static string CAISSE_INEXISTANTE {
            get {
                return ResourceManager.GetString("CAISSE_INEXISTANTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le check digit du compteur est erroné.
        /// </summary>
        internal static string COMPTEUR_CHECKDIGIT_COMPTEUR_ERRONNE {
            get {
                return ResourceManager.GetString("COMPTEUR_CHECKDIGIT_COMPTEUR_ERRONNE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compteur inactif.
        /// </summary>
        internal static string COMPTEUR_INACTIF {
            get {
                return ResourceManager.GetString("COMPTEUR_INACTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compteur inexistant.
        /// </summary>
        internal static string COMPTEUR_INEXISTANT {
            get {
                return ResourceManager.GetString("COMPTEUR_INEXISTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La longueur du compteur est erronée.
        /// </summary>
        internal static string COMPTEUR_LONGUEUR_DRN_ERRONE {
            get {
                return ResourceManager.GetString("COMPTEUR_LONGUEUR_DRN_ERRONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numéro de compteur non numérique.
        /// </summary>
        internal static string COMPTEUR_NUMERO_NON_NUMERIQUE {
            get {
                return ResourceManager.GetString("COMPTEUR_NUMERO_NON_NUMERIQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consommation inférieure à l&apos;unité.
        /// </summary>
        internal static string CONSO_INFERIEUR_UNITE {
            get {
                return ResourceManager.GetString("CONSO_INFERIEUR_UNITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dette antérieure à payer est supérieure au montant de l&apos;achat.
        /// </summary>
        internal static string DETTE_SUP_ACHAT {
            get {
                return ResourceManager.GetString("DETTE_SUP_ACHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les frais fixes et la dette antérieure à payer sont supérieurs au montant de l&apos;achat.
        /// </summary>
        internal static string DETTEPRIMEFIXE_SUP_ACHAT {
            get {
                return ResourceManager.GetString("DETTEPRIMEFIXE_SUP_ACHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longueur du SMS supérieur à 160 caractères.
        /// </summary>
        internal static string ECHEC_ENVOIE_SMS_MESSAGE_TROP_LONG {
            get {
                return ResourceManager.GetString("ECHEC_ENVOIE_SMS_MESSAGE_TROP_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaîne de connexion non définie ou mal configurée.
        /// </summary>
        internal static string ERREUR_CHAINECONNEXION {
            get {
                return ResourceManager.GetString("ERREUR_CHAINECONNEXION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de la division de la consommation sur les tranches.
        /// </summary>
        internal static string FIN_DIVISION_CONSO_TRANCHE {
            get {
                return ResourceManager.GetString("FIN_DIVISION_CONSO_TRANCHE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème lors du chargement des données de base.
        /// </summary>
        internal static string PB_CHARGEMENT_DONNEES_DE_BASE {
            get {
                return ResourceManager.GetString("PB_CHARGEMENT_DONNEES_DE_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème de connexion à la base de données.
        /// </summary>
        internal static string PB_CONNECTION_BASEDEDONNEES {
            get {
                return ResourceManager.GetString("PB_CONNECTION_BASEDEDONNEES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème de fermeture de caisse.
        /// </summary>
        internal static string PB_FERMETURE_DE_CAISSE {
            get {
                return ResourceManager.GetString("PB_FERMETURE_DE_CAISSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème lors de la création du détail de l&apos;achat.
        /// </summary>
        internal static string PB_GENERATION_DETAIL_ACHAT {
            get {
                return ResourceManager.GetString("PB_GENERATION_DETAIL_ACHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème d&apos;ouverture de caisse.
        /// </summary>
        internal static string PB_OUVERTURE_DE_CAISSE {
            get {
                return ResourceManager.GetString("PB_OUVERTURE_DE_CAISSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème lors de la recherche du compteur.
        /// </summary>
        internal static string PB_RECHERCHE_COMPTEUR {
            get {
                return ResourceManager.GetString("PB_RECHERCHE_COMPTEUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème lors de la recherche des redevances de consommation.
        /// </summary>
        internal static string PB_RECHERCHE_TARIF_CONSO {
            get {
                return ResourceManager.GetString("PB_RECHERCHE_TARIF_CONSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème lors de la recherche des redevances fixes.
        /// </summary>
        internal static string PB_RECHERCHE_TARIF_FIXE {
            get {
                return ResourceManager.GetString("PB_RECHERCHE_TARIF_FIXE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problème lors de la validation des achats dans la base de données.
        /// </summary>
        internal static string PB_VALIDATION_ACHAT_BASE {
            get {
                return ResourceManager.GetString("PB_VALIDATION_ACHAT_BASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la période courante est inférieure à la dernière période d&apos;achat.
        /// </summary>
        internal static string PERIODECOURANTE_INF_DERNIEREPERIODE {
            get {
                return ResourceManager.GetString("PERIODECOURANTE_INF_DERNIEREPERIODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les frais fixes sont supérieurs au montant de l&apos;achat.
        /// </summary>
        internal static string PRIMEFIXE_SUP_ACHAT {
            get {
                return ResourceManager.GetString("PRIMEFIXE_SUP_ACHAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une session est déjà ouverte sur cette caisse par un autre utilisateur.
        /// </summary>
        internal static string SESSION_AUTRE_UTILISATEUR_OUVERTE {
            get {
                return ResourceManager.GetString("SESSION_AUTRE_UTILISATEUR_OUVERTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une session est déjà ouverte pour cet utilisateur.
        /// </summary>
        internal static string SESSION_UTILISATEUR_OUVERTE {
            get {
                return ResourceManager.GetString("SESSION_UTILISATEUR_OUVERTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur sur le TokenAmount.
        /// </summary>
        internal static string TOKENAMOUNT_ERREUR {
            get {
                return ResourceManager.GetString("TOKENAMOUNT_ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur sur la classe du TokenData.
        /// </summary>
        internal static string TOKENCLASS_ERREUR {
            get {
                return ResourceManager.GetString("TOKENCLASS_ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur sur le TokenCRC.
        /// </summary>
        internal static string TOKENCRC_ERREUR {
            get {
                return ResourceManager.GetString("TOKENCRC_ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur sur la date du TokenID.
        /// </summary>
        internal static string TOKENID_DATE_ERREUR {
            get {
                return ResourceManager.GetString("TOKENID_DATE_ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur sur le TokenID.
        /// </summary>
        internal static string TOKENID_ERREUR {
            get {
                return ResourceManager.GetString("TOKENID_ERREUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur sur le subclass du TokenData.
        /// </summary>
        internal static string TOKENSUBCLASS_ERREUR {
            get {
                return ResourceManager.GetString("TOKENSUBCLASS_ERREUR", resourceCulture);
            }
        }
    }
}
