//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model.Fraude
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        public CLIENT()
        {
            this.FRAUDE = new HashSet<FRAUDE>();
        }
    
        public System.Guid Id { get; set; }
        public string Site { get; set; }
        public string Centre { get; set; }
        public string Client1 { get; set; }
        public string Ordre { get; set; }
        public string IdentificationUnique { get; set; }
        public string Nomabon { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Commune { get; set; }
        public string Quartier { get; set; }
        public string Rue { get; set; }
        public string Porte { get; set; }
        public string Tournee { get; set; }
        public string OrdreTournee { get; set; }
        public string Secteur { get; set; }
        public string ContratAbonnement { get; set; }
        public Nullable<System.DateTime> DateContratAbonnement { get; set; }
        public string ContratBranchement { get; set; }
        public Nullable<System.DateTime> DateContratBranchement { get; set; }
        public Nullable<decimal> Puissance { get; set; }
    
        public virtual CENTRE CENTRE1 { get; set; }
        public virtual ICollection<FRAUDE> FRAUDE { get; set; }
    }
}
