//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model.Fraude
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETAPEFRAUDE
    {
        public ETAPEFRAUDE()
        {
            this.FRAUDE = new HashSet<FRAUDE>();
        }
    
        public int Id { get; set; }
        public int NumEtape { get; set; }
        public int IdTache { get; set; }
        public string IdFonction { get; set; }
        public Nullable<byte> DelaiExecutionEtape { get; set; }
    
        public virtual ICollection<FRAUDE> FRAUDE { get; set; }
    }
}
