//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model.Fraude
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRAUDE
    {
        public System.Guid Id { get; set; }
        public System.Guid IdAbonne { get; set; }
        public Nullable<System.Guid> IdDenonciateur { get; set; }
        public byte IdSource { get; set; }
        public Nullable<byte> IdDecisionFraude { get; set; }
        public Nullable<bool> IsConvocationRespectee { get; set; }
        public Nullable<bool> IsFraudeConfirmee { get; set; }
        public Nullable<float> MontantCaution { get; set; }
        public Nullable<System.DateTime> DateReclamation { get; set; }
        public string MotifReclamation { get; set; }
        public int IdEtape { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.DateTime DateEtape { get; set; }
        public string FicheTraitement { get; set; }
        public byte Ordre { get; set; }
        public string BordereauTransmission { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual DENONCIATEUR DENONCIATEUR { get; set; }
        public virtual ETAPEFRAUDE ETAPEFRAUDE { get; set; }
        public virtual SOURCECONTROLE SOURCECONTROLE { get; set; }
    }
}
