//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model.Fraude
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FRAUDES_Entities : DbContext
    {
        public FRAUDES_Entities()
            : base("name=FRAUDES_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CENTRE> CENTRE { get; set; }
        public DbSet<CLIENT> CLIENT { get; set; }
        public DbSet<DENONCIATEUR> DENONCIATEUR { get; set; }
        public DbSet<ETAPEFRAUDE> ETAPEFRAUDE { get; set; }
        public DbSet<FRAUDE> FRAUDE { get; set; }
        public DbSet<SOURCECONTROLE> SOURCECONTROLE { get; set; }
    
        public virtual ObjectResult<string> spx_FicheTraitement_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spx_FicheTraitement_Select");
        }
    }
}
